/*
 * Generates the Material Symbols set from the library's assets.
 *
 * Like Phosphor, Material does not publish data: it publishes `.svg` files. The why of the codegen is
 * in decision 15: it converts a format no bundler converts on its own, so it passes the deletion test
 * the manifest generator did not.
 *
 * And this set is the one that proved IconData was wrong: Material draws in `viewBox="0 -960 960 960"`,
 * which does NOT start at `0 0`. The original width/height pair assembled `0 0 w h` and would have
 * clipped every icon in this set. Lucide (0 0 24 24) and Phosphor (0 0 256 256) hid the flaw.
 *
 * The shell (--check, the template, the `<svg>` extraction) is shared by all three sets and lives in
 * @skryensya/core/emit-icon-set. What is left here is only what varies: the MAP, the ATTRS, the header,
 * and the asset spec. `resolve` runs in THIS module on purpose: `import.meta.resolve` has to see
 * Material's devDependency, which core does not have.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { generateIconSet, extractSvgBody } from "@skryensya/core/emit-icon-set";

/* System role → Material's name. Here the distance is the largest of the three sets: `arrow-left` is
 * its `arrow_back`, `more` is `more_horiz`, `user` is `person`. None of that leaks to the call site,
 * which is the point. */
const MAP = {
  "chevron-up": "keyboard_arrow_up",
  "chevron-down": "keyboard_arrow_down",
  "chevron-left": "chevron_left",
  "chevron-right": "chevron_right",
  "arrow-up": "arrow_upward",
  "vote-up": "thumb_up",
  "vote-down": "thumb_down",
  "arrow-down": "arrow_downward",
  "arrow-left": "arrow_back",
  "arrow-right": "arrow_forward",
  "external-link": "open_in_new",
  add: "add",
  remove: "remove",
  close: "close",
  check: "check",
  search: "search",
  edit: "edit",
  delete: "delete",
  copy: "content_copy",
  filter: "filter_alt",
  refresh: "refresh",
  "zoom-out": "zoom_out",
  more: "more_horiz",
  menu: "menu",
  info: "info",
  success: "check_circle",
  warning: "warning",
  danger: "cancel",
  calendar: "calendar_today",
  clock: "schedule",
  upload: "upload",
  download: "download",
  file: "description",
  folder: "folder",
  settings: "settings",
  user: "person",
  language: "translate",
  visibility: "visibility",
  "visibility-off": "visibility_off",
  "mode-system": "monitor",
  "mode-light": "light_mode",
  "mode-dark": "dark_mode",
  "screen-desktop": "monitor",
  /* `tablet` / `mobile`, not `tablet_mac` / `phone_iphone`: Material offers both, and the one that names
   * a vendor is the one that ages badly when the set changes style. */
  "screen-tablet": "tablet",
  "screen-mobile": "mobile",
};

/* Material's assets do NOT declare fill: their `<path>` elements would inherit the browser's default,
 * which is black, an icon that ignores its container's color and is invisible in dark mode. Declaring
 * it here is what makes it correct across the eight brands and both modes. */
const ATTRS = { fill: "currentColor" };

const STYLE = "outlined";

const HEADER = `/*
 * GENERATED by scripts/generate.ts, do not edit by hand.
 *
 * Material Symbols geometry (Apache-2.0), "${STYLE}" style, weight 400, redistributed under its
 * license. See LICENSE-material.
 */`;

/** Material's adapter: resolve the `.svg` asset from the devDependency and extract its body. */
const resolve = (name: string, role: string) => {
  const spec = `@material-symbols/svg-400/${STYLE}/${name}.svg`;
  let path;
  try {
    path = fileURLToPath(import.meta.resolve(spec));
  } catch {
    throw new Error(`Material no tiene "${name}" (rol "${role}"), ¿se renombró en un upgrade?`);
  }
  return extractSvgBody(readFileSync(path, "utf8"), name);
};

generateIconSet({ dir: import.meta.dirname, label: "material", map: MAP, attrs: ATTRS, header: HEADER, resolve });
