// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/accordion.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/accordion.css";
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/details.css";
import "@skryensya/core/components/diagram.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/accordion";
const { accordionAnatomyCss, accordionChoiceCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/Accordion", tags: ["autodocs"] } satisfies Meta;

export const DetailsAnatomy: StoryObj = treeStory(demos.detailsAnatomyTree, { decorators: [withCss(accordionAnatomyCss)] });
export const Choice: StoryObj = treeStory(demos.accordionChoiceTree, { decorators: [withCss(accordionChoiceCss)] });
export const Single: StoryObj = treeStory(demos.accordionSingleTree);
export const Exclusive: StoryObj = treeStory(demos.accordionExclusiveTree);
export const DetailsGroup: StoryObj = treeStory(demos.detailsGroupTree);
export const Multiple: StoryObj = treeStory(demos.accordionMultipleTree);
