// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/anchoring.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/tooltip.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/anchoring";
import { treeStory } from "../tree-story";

export default { title: "Foundations/Anchoring", tags: ["autodocs"] } satisfies Meta;

export const AnchorPlacements: StoryObj = treeStory(() => demos.anchorPlacementsTree);
