// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/annotation.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/accordion.css";
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/breadcrumb.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/details.css";
import "@skryensya/core/components/menu.css";
import "@skryensya/core/components/stat.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/annotation";
const { annotationDemoCss, annotationSelfAnatomyCss, annotationPluralCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/Annotation", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.annotationAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const SelfAnatomy: StoryObj = treeStory(demos.annotationSelfAnatomyTree, { decorators: [withCss(annotationSelfAnatomyCss)] });
export const Sides: StoryObj = treeStory(demos.annotationSidesTree, { decorators: [withCss(annotationDemoCss)] });
export const Plural: StoryObj = treeStory(demos.annotationPluralTree, { decorators: [withCss(annotationPluralCss)] });
export const Elbow: StoryObj = treeStory(demos.annotationElbowTree, { decorators: [withCss(annotationDemoCss)] });
