// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/app-shell.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/navbar.css";
import "@skryensya/core/components/sidebar.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/nav-list.css";
import "@skryensya/core/patterns/splitter.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/app-shell";
import { treeStory } from "../tree-story";

export default { title: "Foundations/AppShell", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.appShellTree);
export const Explorer: StoryObj = treeStory(demos.appShellExplorerTree);
