// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/avatar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/avatar";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/Avatar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.avatarAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const GroupAnatomy: StoryObj = treeStory(demos.avatarGroupAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Image: StoryObj = treeStory(demos.avatarImageTree);
export const Sizes: StoryObj = treeStory(demos.avatarSizesTree);
export const Colors: StoryObj = treeStory(demos.avatarColorsTree);
export const Group: StoryObj = treeStory(demos.avatarGroupTree);
export const Profile: StoryObj = treeStory(demos.avatarProfileTree);
