// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/back-to-top.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/back-to-top.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/back-to-top";
const { backToTopAnatomyCss, backToTopDemoCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Navigation/BackToTop", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.backToTopAnatomyTree, { decorators: [withCss(backToTopAnatomyCss)] });
export const Default: StoryObj = treeStory(demos.backToTopTree, { decorators: [withCss(backToTopDemoCss)] });
export const Scroll: StoryObj = treeStory(demos.backToTopScrollTree, { decorators: [withCss(backToTopDemoCss)] });
