// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/breadcrumb.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/breadcrumb.css";
import "@skryensya/core/components/menu.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/icon.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/breadcrumb";
import { treeStory } from "../tree-story";

export default { title: "Components/Navigation/Breadcrumb", tags: ["autodocs"] } satisfies Meta;

export const Two: StoryObj = treeStory(demos.breadcrumbTwoTree);
export const Multi: StoryObj = treeStory(demos.breadcrumbMultiTree);
export const Icon: StoryObj = treeStory(demos.breadcrumbIconTree);
export const Long: StoryObj = treeStory(demos.breadcrumbLongTree);
export const Collapse: StoryObj = treeStory(demos.breadcrumbCollapseTree);
