// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/calendar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/calendar.css";
import "@skryensya/core/components/canvas.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/calendar";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Forms/Calendar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.calendarAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.calendarTree);
export const Range: StoryObj = treeStory(demos.calendarRangeTree);
export const MinMax: StoryObj = treeStory(demos.calendarMinMaxTree);
