// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/carousel.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/carousel.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/carousel";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/Carousel", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.carouselAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Cards: StoryObj = treeStory(demos.carouselCardsTree);
export const Autoplay: StoryObj = treeStory(demos.carouselAutoplayTree);
export const Focusable: StoryObj = treeStory(demos.carouselFocusableTree);
export const Bare: StoryObj = treeStory(demos.carouselBareTree);
export const Native: StoryObj = treeStory(demos.carouselNativeTree);
