// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/charts.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/chart.css";
import "@skryensya/core/components/segmented.css";
import "@skryensya/core/components/stat.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/components/tabs.css";
import "@skryensya/core/components/tooltip.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/charts";
const { chartsAnatomyCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Data/Charts", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.chartsAnatomyTree, { decorators: [withCss(chartsAnatomyCss)] });
export const ChartHistoryCard: StoryObj = treeStory(demos.chartHistoryCardTree);
export const ChartUsageCard: StoryObj = treeStory(demos.chartUsageCardTree);
export const Bar: StoryObj = treeStory(demos.chartsBarTree);
export const ChartTableCard: StoryObj = treeStory(demos.chartTableCardTree);
export const ChartPointDetail: StoryObj = treeStory(demos.chartPointDetailTree);
export const ChartMetricTabs: StoryObj = treeStory(demos.chartMetricTabsTree);
export const ChartLegendCard: StoryObj = treeStory(demos.chartLegendCardTree);
export const ChartAnalyticsCard: StoryObj = treeStory(demos.chartAnalyticsCardTree);
export const Line: StoryObj = treeStory(demos.chartsLineTree);
export const Area: StoryObj = treeStory(demos.chartsAreaTree);
export const ChartGallery: StoryObj = treeStory(demos.chartGalleryTree);
export const ChartComparison: StoryObj = treeStory(demos.chartComparisonTree);
export const ChartPeriodCard: StoryObj = treeStory(demos.chartPeriodCardTree);
