// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/clipboard.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/clipboard.css";
import "@skryensya/core/components/copy-button.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/clipboard";
const { clipboardAnatomyCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Actions/Clipboard", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.clipboardAnatomyTree, { decorators: [withCss(clipboardAnatomyCss)] });
export const Target: StoryObj = treeStory(demos.clipboardTargetTree);
export const Field: StoryObj = treeStory(demos.clipboardFieldTree);
export const Sizes: StoryObj = treeStory(demos.clipboardSizesTree);
