// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/code-preview.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/code-preview.css";
import "@skryensya/core/components/switch.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/code-preview";
import { treeStory } from "../tree-story";

export default { title: "Components/Content/CodePreview", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.codePreviewTree);
