// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/color-picker.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/color-picker.css";
import "@skryensya/core/patterns/anchored.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/color-picker";
import { treeStory } from "../tree-story";

export default { title: "Components/Forms/ColorPicker", tags: ["autodocs"] } satisfies Meta;

export const NativeColorPicker: StoryObj = treeStory(demos.nativeColorPickerTree);
export const Default: StoryObj = treeStory(demos.colorPickerTree);
export const CompactColorPicker: StoryObj = treeStory(demos.compactColorPickerTree);
export const PresetsColorPicker: StoryObj = treeStory(demos.presetsColorPickerTree);
export const DisabledColorPicker: StoryObj = treeStory(demos.disabledColorPickerTree);
