// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/combobox.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/combobox.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/visually-hidden.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/combobox";
import { localeOf } from "../translate";
import { treeStory } from "../tree-story";

export default { title: "Components/Forms/Combobox", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory((t) => demos.comboboxTree(t, localeOf(t)));
