// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/command-palette.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/command-palette.css";
import "@skryensya/core/components/dialog.css";
import "@skryensya/core/patterns/dialog-vaul.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/command-palette";
import { treeStory } from "../tree-story";

export default { title: "Components/Actions/CommandPalette", tags: ["autodocs"] } satisfies Meta;

export const Demo: StoryObj = treeStory(demos.commandPaletteDemoTree);
