// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/data-grid.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/data-grid.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/data-grid";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Unlisted/DataGrid", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.dataGridAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Scores: StoryObj = treeStory(demos.dataGridScoresTree);
export const Actions: StoryObj = treeStory(demos.dataGridActionsTree);
