// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/editor.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/editor.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/popover.css";
import "@skryensya/core/components/toolbar.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/editor";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Forms/Editor", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.editorAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.editorTree);
export const Compact: StoryObj = treeStory(demos.editorCompactTree);
