// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/empty-state.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/empty-state.css";
import "@skryensya/core/patterns/icon.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/empty-state";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Feedback/EmptyState", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.emptyStateAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.emptyStateTree);
