// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/feed.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/feed.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/components/placeholder.css";
import "@skryensya/core/components/tag.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/feed";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/Feed", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.feedAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.feedTree);
export const Activity: StoryObj = treeStory(demos.feedActivityTree);
export const Busy: StoryObj = treeStory(demos.feedBusyTree);
export const Infinite: StoryObj = treeStory(demos.feedInfiniteTree);
export const Comments: StoryObj = treeStory(demos.feedCommentsTree);
