// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/file-upload.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/file-upload.css";
import * as demos from "@docs/demos/file-upload";
import { treeStory, type Meta, type StoryObj } from "@story";

export default { title: "Components/Forms/FileUpload", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.fileUploadTree);
export const PageDrop: StoryObj = treeStory(demos.fileUploadPageDropTree);
