// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/icons.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/icons";
import { treeStory } from "../tree-story";

export default { title: "Foundations/Icons", tags: ["autodocs"] } satisfies Meta;

export const IconVocab: StoryObj = treeStory(() => demos.iconVocabTree);
