// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/icon.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/icon";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/Icon", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.iconAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(() => demos.iconTree);
export const Size: StoryObj = treeStory(() => demos.iconSizeTree);
