// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/image-frame.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/image-frame";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/ImageFrame", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.imageFrameAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.imageFrameTree);
export const Aspect: StoryObj = treeStory(demos.imageFrameAspectTree);
export const Fit: StoryObj = treeStory(demos.imageFrameFitTree);
export const Position: StoryObj = treeStory(demos.imageFramePositionTree);
