// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/input.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/input";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Forms/Input", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.inputAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.inputTree);
export const Textarea: StoryObj = treeStory(demos.textareaTree);
export const Format: StoryObj = treeStory(demos.inputFormatTree);
