// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/lightbox.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/lightbox.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import "@skryensya/core/patterns/scroll-lock.css";
import "@skryensya/core/patterns/visually-hidden.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/lightbox";
const { lightboxDemoCss } = demos;
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Overlays/Lightbox", tags: ["autodocs"] } satisfies Meta;

export const Gallery: StoryObj = treeStory(demos.lightboxGalleryTree, { decorators: [withCss(lightboxDemoCss)] });
export const Single: StoryObj = treeStory(demos.lightboxSingleTree, { decorators: [withCss(lightboxDemoCss)] });
export const Loop: StoryObj = treeStory(demos.lightboxLoopTree, { decorators: [withCss(lightboxDemoCss)] });
