// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/list.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/list.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/list";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Data/List", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.listAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Plain: StoryObj = treeStory(demos.listPlainTree);
export const Titled: StoryObj = treeStory(demos.listTitledTree);
export const Leading: StoryObj = treeStory(demos.listLeadingTree);
export const Trailing: StoryObj = treeStory(demos.listTrailingTree);
export const Links: StoryObj = treeStory(demos.listLinksTree);
export const Full: StoryObj = treeStory(demos.listFullTree);
