// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/marquee.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/marquee.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import "@skryensya/core/patterns/visually-hidden.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/marquee";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/Marquee", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.marqueeAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Manual: StoryObj = treeStory(demos.marqueeManualTree);
export const Autoplay: StoryObj = treeStory((t) => demos.marqueeAutoplayTree());
export const Control: StoryObj = treeStory(demos.marqueeControlTree);
export const Badge: StoryObj = treeStory(demos.marqueeBadgeTree);
export const Avatar: StoryObj = treeStory(demos.marqueeAvatarTree);
export const Vertical: StoryObj = treeStory(demos.marqueeVerticalTree);
export const NoFade: StoryObj = treeStory((t) => demos.marqueeNoFadeTree());
