// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/media-gradient.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import * as demos from "@docs/demos/media-gradient";
import { treeStory, type Meta, type StoryObj } from "@story";

export default { title: "Foundations/MediaGradient", tags: ["autodocs"] } satisfies Meta;

export const Card: StoryObj = treeStory(demos.mediaGradientCardTree);
export const Edges: StoryObj = treeStory((t) => demos.mediaGradientEdgesTree());
