// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/megamenu.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/megamenu.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/media-gradient.css";
import "@skryensya/core/patterns/nav-list.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/megamenu";
import { treeStory } from "../tree-story";

export default { title: "Components/Navigation/Megamenu", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.megamenuTree);
