// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/navbar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/navbar.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/nav-list.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/navbar";
import { annotationDemoCss } from "@docs/demos/annotation";
const { navbarBareCss } = demos;
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Navigation/Navbar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.navbarAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.navbarTree);
export const Bare: StoryObj = treeStory(demos.navbarBareTree, { decorators: [withCss(navbarBareCss)] });
export const App: StoryObj = treeStory(demos.navbarAppTree);
