// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/pagination.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/pagination.css";
import * as demos from "@docs/demos/pagination";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Navigation/Pagination", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.paginationAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.paginationTree);
