// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/password-input.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/password-input.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/password-input";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Forms/PasswordInput", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.passwordInputAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const SignIn: StoryObj = treeStory(demos.passwordInputSignInTree);
export const SignUp: StoryObj = treeStory(demos.passwordInputSignUpTree);
export const States: StoryObj = treeStory(demos.passwordInputStatesTree);
