// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/placeholder.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/placeholder.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/placeholder";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Feedback/Placeholder", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.placeholderAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const PublicationPlaceholder: StoryObj = treeStory(demos.publicationPlaceholderTree);
export const PublicationSwap: StoryObj = treeStory(demos.publicationSwapTree);
export const Vocabulary: StoryObj = treeStory((t) => demos.placeholderVocabularyTree());
export const Match: StoryObj = treeStory(demos.placeholderMatchTree);
