// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/popover.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/popover.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/popover";
import { treeStory } from "../tree-story";

export default { title: "Components/Overlays/Popover", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.popoverTree);
export const Structured: StoryObj = treeStory(demos.popoverStructuredTree);
export const Placement: StoryObj = treeStory(demos.popoverPlacementTree);
export const Popup: StoryObj = treeStory(demos.popupTree);
