// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/presence.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/callout.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/presence.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/presence";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Layout/Presence", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.presenceAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Notice: StoryObj = treeStory(demos.presenceNoticeTree);
export const Fields: StoryObj = treeStory(demos.presenceFieldsTree);
export const Tuning: StoryObj = treeStory(demos.presenceTuningTree);
