// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/process-list.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/code-preview.css";
import "@skryensya/core/components/process-list.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/process-list";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/ProcessList", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.processListAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.processListTree);
