// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/qr-code.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/popover.css";
import "@skryensya/core/components/qr-code.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/qr-code";
import { annotationDemoCss } from "@docs/demos/annotation";
import { localeOf } from "../translate";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/QRCode", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory((t) => demos.qrCodeAnatomyTree(t, localeOf(t)), { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory((t) => demos.qrCodeTree(localeOf(t)));
export const Sizes: StoryObj = treeStory((t) => demos.qrCodeSizesTree(localeOf(t)));
export const Levels: StoryObj = treeStory((t) => demos.qrCodeLevelsTree(localeOf(t)));
export const Shapes: StoryObj = treeStory((t) => demos.qrCodeShapesTree(localeOf(t)));
export const Masks: StoryObj = treeStory((t) => demos.qrCodeMasksTree(localeOf(t)));
export const Tones: StoryObj = treeStory((t) => demos.qrCodeTonesTree(localeOf(t)));
export const Logo: StoryObj = treeStory((t) => demos.qrCodeLogoTree(localeOf(t)));
export const Card: StoryObj = treeStory((t) => demos.qrCodeCardTree(localeOf(t)));
export const Popover: StoryObj = treeStory((t) => demos.qrCodePopoverTree(localeOf(t)));
export const Ticket: StoryObj = treeStory((t) => demos.qrCodeTicketTree(localeOf(t)));
