// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/quote.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/quote.css";
import "@skryensya/core/patterns/box.css";
import * as demos from "@docs/demos/quote";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/Quote", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.quoteAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.quoteTree);
export const Bare: StoryObj = treeStory(demos.quoteBareTree);
export const Pull: StoryObj = treeStory(demos.quotePullTree);
export const Testimonial: StoryObj = treeStory(demos.quoteTestimonialTree);
