// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/scrollbar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/scrollbar";
import { treeStory, type Meta, type StoryObj } from "@story";

export default { title: "Foundations/Scrollbar", tags: ["autodocs"] } satisfies Meta;

export const Always: StoryObj = treeStory(demos.scrollbarAlwaysTree);
export const Reveal: StoryObj = treeStory(demos.scrollbarRevealTree);
