// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/select.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/patterns/anchored.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/select";
import { treeStory } from "../tree-story";

export default { title: "Components/Forms/Select", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.selectTree);
export const Native: StoryObj = treeStory(demos.selectNativeTree);
