// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/separator.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/separator.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/separator";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Layout/Separator", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.separatorAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.separatorTree);
export const Tones: StoryObj = treeStory(demos.separatorTonesTree);
export const Vertical: StoryObj = treeStory(demos.separatorVerticalTree);
export const Labelled: StoryObj = treeStory(demos.separatorLabelledTree);
