// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/sidebar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/sidebar.css";
import "@skryensya/core/components/tree-view.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/nav-list.css";
import "@skryensya/core/patterns/splitter.css";
import * as demos from "@docs/demos/sidebar";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Navigation/Sidebar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.sidebarAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.sidebarTree);
export const Resizable: StoryObj = treeStory(demos.sidebarResizableTree);
export const FloatingTrigger: StoryObj = treeStory(demos.sidebarFloatingTriggerTree);
