// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/split-button.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/menu.css";
import "@skryensya/core/components/split-button.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/split-button";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Actions/SplitButton", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.splitButtonAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.splitButtonTree);
export const Small: StoryObj = treeStory(demos.splitButtonSmallTree);
export const MenuFirst: StoryObj = treeStory(demos.splitButtonMenuFirstTree);
export const Subtle: StoryObj = treeStory(demos.splitButtonSubtleTree);
export const Translucent: StoryObj = treeStory(demos.splitButtonTranslucentTree);
export const Ghost: StoryObj = treeStory(demos.splitButtonGhostTree);
export const Danger: StoryObj = treeStory(demos.splitButtonDangerTree);
