// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/state-button.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/state-button.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/state-button";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Actions/StateButton", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.stateButtonAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Basic: StoryObj = treeStory(demos.stateButtonBasicTree);
export const ThemeToggle: StoryObj = treeStory(demos.stateButtonThemeToggleTree);
export const Copy: StoryObj = treeStory(demos.stateButtonCopyTree);
