// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/state-layer.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/state-layer";
import { treeStory } from "../tree-story";

export default { title: "Foundations/StateLayer", tags: ["autodocs"] } satisfies Meta;

export const Bare: StoryObj = treeStory(demos.stateLayerBareTree);
export const CurrentColor: StoryObj = treeStory(demos.stateLayerCurrentColorTree);
export const Lab: StoryObj = treeStory(demos.stateLayerLabTree);
