// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/steps.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/steps.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/steps";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Navigation/Steps", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.stepsAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.stepsTree);
export const Vertical: StoryObj = treeStory(demos.stepsVerticalTree);
