// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/sticker.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/sticker.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/sticker";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/Sticker", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.stickerAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.stickerTree);
export const States: StoryObj = treeStory(demos.stickerStatesTree);
export const Placement: StoryObj = treeStory(demos.stickerPlacementTree);
export const Origins: StoryObj = treeStory(demos.stickerOriginsTree);
export const Hooks: StoryObj = treeStory(demos.stickerHooksTree);
