// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/styling-hooks.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/styling-hooks";
import { treeStory } from "../tree-story";

export default { title: "Foundations/StylingHooks", tags: ["autodocs"] } satisfies Meta;

export const StylingHookOverride: StoryObj = treeStory(demos.stylingHookOverrideTree);
