// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/table.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/pagination.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/table-pager.css";
import * as demos from "@docs/demos/table";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Data/Table", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tableAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.tableTree);
export const StickyColumn: StoryObj = treeStory(demos.tableStickyColumnTree);
export const StickyHeader: StoryObj = treeStory(demos.tableStickyHeaderTree);
export const ResizableColumns: StoryObj = treeStory(demos.tableResizableColumnsTree);
export const Pager: StoryObj = treeStory(demos.tablePagerTree);
export const InBox: StoryObj = treeStory(demos.tableInBoxTree);
export const Density: StoryObj = treeStory(demos.tableDensityTree);
