// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/tabs.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/tabs.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/tabs";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Navigation/Tabs", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tabsAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Basic: StoryObj = treeStory(demos.tabsBasicTree);
export const States: StoryObj = treeStory(demos.tabsStatesTree);
export const Advanced: StoryObj = treeStory(demos.tabsAdvancedTree);
export const Size: StoryObj = treeStory(demos.tabsSizeTree);
export const Hanging: StoryObj = treeStory(demos.tabsHangingTree);
