// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/tag.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/tag.css";
import "@skryensya/core/patterns/layout.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/tag";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Content/Tag", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tagAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Simple: StoryObj = treeStory(demos.tagSimpleTree);
export const Tones: StoryObj = treeStory(demos.tagTonesTree);
export const Links: StoryObj = treeStory(demos.tagLinksTree);
export const Removable: StoryObj = treeStory(demos.tagRemovableTree);
