// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/tile.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import * as demos from "@docs/demos/tile";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Content/Tile", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tileAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const ExpandableTile: StoryObj = treeStory(demos.expandableTileTree);
export const LinkDemo: StoryObj = treeStory(demos.tileLinkDemoTree);
export const ButtonDemo: StoryObj = treeStory(demos.tileButtonDemoTree);
