// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/time-field.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/components/time-field.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/time-field";
import { treeStory, type Meta, type StoryObj } from "@story";

export default { title: "Components/Forms/TimeField", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.timeFieldTree);
export const Forced24: StoryObj = treeStory(demos.timeFieldForced24Tree);
export const QuarterHour: StoryObj = treeStory(demos.timeFieldQuarterHourTree);
export const Native: StoryObj = treeStory(demos.timeFieldNativeTree);
