// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/toc.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/toc.css";
import "@skryensya/core/patterns/icon.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/toc";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss } from "../tree-story";

export default { title: "Components/Navigation/Table of contents", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tocAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Plain: StoryObj = treeStory(demos.tocPlainTree);
export const Nested: StoryObj = treeStory(demos.tocNestedTree);
export const Icons: StoryObj = treeStory(demos.tocIconsTree);
