// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/toolbar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/segmented.css";
import "@skryensya/core/components/toolbar.css";
import "@skryensya/core/components/tooltip.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/toolbar";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Actions/Toolbar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.toolbarAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.toolbarTree);
export const NestedToolbar: StoryObj = treeStory(demos.nestedToolbarTree);
