// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/tour.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/segmented.css";
import "@skryensya/core/components/tour.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/tour";
const { tourDemoCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "@story";

export default { title: "Components/Overlays/Tour", tags: ["autodocs"] } satisfies Meta;

export const Basic: StoryObj = treeStory(demos.tourBasicTree, { decorators: [withCss(tourDemoCss)] });
export const Missing: StoryObj = treeStory(demos.tourMissingTree, { decorators: [withCss(tourDemoCss)] });
