// GENERATED by scripts/generate-stories.ts from apps/docs/src/demos/wrapper.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate`.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/wrapper.css";
import type { Meta, StoryObj } from "@storybook/react-vite";
import * as demos from "@docs/demos/wrapper";
import { treeStory } from "../tree-story";

export default { title: "Components/Layout/Wrapper", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.wrapperTree);
