export const timeFieldMessages = {
  es: {
    "demo.timeField.label": "Salida",
    "demo.timeField.forced24Label": "Llegada (24 horas)",

    "timeFieldPage.description": "Un campo de hora segmentado con un desplegable integrado: hora, minuto y AM/PM como partes editables, más una lista de horarios preestablecidos, todo operable por teclado.",
    "timeFieldPage.lede":
      'Un campo para una hora de reloj local, sin fecha, sin zona horaria. Hora, minuto y (en un locale de 12 horas) AM/PM son tres segmentos editables independientes en un solo campo, en vez del chrome del propio <code>&lt;input type="time"&gt;</code>, que difiere lo suficiente entre Chrome, Firefox y Safari como para no poder estilarse ni confiar en que se vea igual dos veces. No existe una machine <code>@zag-js/time-picker</code> para esos segmentos, así que esa parte es estado a mano, como Slider y Segmented: pero SÍ hay un desplegable, siempre presente, con una lista simple y navegable con flechas (nada de buscador: para una lista acotada y ordenada, uno de más). Dos cosas se probaron y se descartaron antes de llegar ahí: un selector de ruedas (ni más simple ni más accesible que los segmentos mismos) y una lista con buscador tipo Combobox (demasiada máquina para una lista corta).',
    "timeFieldPage.contractBody":
      "El orden de los segmentos y el separador entre ellos se leen del propio <code>formatToParts</code> de <code>Intl.DateTimeFormat</code>, no se asumen: algunos locales ponen el periodo del día antes de la hora, y el separador no siempre es <code>\":\"</code>. El valor público sigue siendo el string canónico <code>HH:mm</code>, la misma forma que envía un <code>&lt;input type=\"time\"&gt;</code> plano, llevado en un input oculto, así que un formulario detrás de TimeField nunca tiene que parsear un string dependiente del locale. React lo guarda como estado del componente (<code>value</code>/<code>defaultValue</code>, un callback <code>onValueChange</code>). Vanilla hidrata el <code>data-sk-time-field</code> autorado: el consumidor sólo autora la raíz y su label, y el componente genera los segmentos a partir de <code>data-locale</code>.",
    "timeFieldPage.editTitle": "Editar un segmento",
    "timeFieldPage.editBody":
      'Escribir un dígito llena el segmento enfocado y avanza en cuanto ningún otro dígito podría mantenerlo válido: escribir <kbd class="sk-kbd">1</kbd> en el segmento de hora de un campo de 12 horas espera brevemente un posible segundo dígito (<code>10</code>–<code>12</code>), escribir <kbd class="sk-kbd">9</kbd> avanza de inmediato, porque ningún segundo dígito podría seguirlo y seguir siendo ≤ 12. Las flechas arriba/abajo suben o bajan el valor y dan la vuelta en los extremos; <kbd class="sk-kbd">Retroceso</kbd> limpia el segmento; <kbd class="sk-kbd">←</kbd>/<kbd class="sk-kbd">→</kbd> mueven entre segmentos; escribir la primera letra de la etiqueta AM/PM del locale en ese segmento lo fija directamente.',
    "timeFieldPage.forced24Title": "Forzar 24 horas, sin depender del locale",
    "timeFieldPage.forced24Body":
      'La detección automática (<code>getHourCycle</code>) lee <code>Intl.DateTimeFormat(locale, {hour:"numeric"}).resolvedOptions().hourCycle</code>, y ese dato resultó inconsistente entre motores: el mismo string de locale (<code>es</code>/<code>es-AR</code>) resuelve a ciclos opuestos en Node y en un Chromium real. Como el máximo del segmento de hora sale directo de ese ciclo, una detección equivocada no sólo mostraba mal la hora: adelantaba el foco antes de tiempo al tipear un primer dígito ambiguo (un «2», que todavía podía volverse «22»). La opción <code>hourCycle</code> pisa la detección cuando se necesita un campo de 24 horas garantizado, sin importar el navegador.',
    "timeFieldPage.nativeTitle": "Si sólo necesitas el selector de la plataforma",
    "timeFieldPage.nativeBody":
      'Un <code>&lt;input type="time"&gt;</code> plano sigue funcionando, no necesita CSS ni JavaScript, y trae gratis el teclado y selector del sistema operativo. Sube a TimeField sólo cuando la inconsistencia de ese selector entre navegadores, o la ausencia total de hooks de estilo, realmente te cuesta algo, la misma decisión que DatePicker toma contra un <code>type="date"</code> plano.',
    "timeFieldPage.nativeLabel": "Input de hora nativo",
    "timeFieldPage.optionsTitle": "El desplegable, con otro paso",
    "timeFieldPage.optionsBody":
      'El botón de reloj pinta DENTRO de <code>.sk-time-field__control</code>: una sola caja con borde, la misma anatomía que ya tiene el control de Combobox para sus propios botones finales: y abre una lista simple, sin buscador, navegable con flechas: <code>@zag-js/select</code> maneja esa máquina directamente (la misma que usa <code>Select</code>), sin montar el componente <code>Select</code> completo, que trae su propio trigger visible y hubiera significado dos clics para llegar a la lista. La opción <code>optionsStep</code> (30 minutos por defecto, 48 filas) decide cada cuánto aparece una fila; <code>Alt+Flecha-abajo</code> desde cualquier segmento la abre sin pasar por Tab, la misma tecla que ya abre un <code>&lt;select&gt;</code> nativo.',
    "timeFieldPage.optionsQuarterHourTitle": "Cada 15 minutos",
    "timeFieldPage.a11yBody":
      'Cada segmento es <code>role="spinbutton"</code> dentro de un <code>role="group"</code> nombrado por el label del campo: <code>aria-valuenow</code>/<code>aria-valuetext</code> llevan su valor actual (un placeholder amistoso como «hh» antes de fijar nada, no un string vacío), y <code>aria-valuemin</code>/<code>aria-valuemax</code> su rango real: 1–12 para un segmento de hora en un locale de 12 horas, 0–23 en uno de 24. Cada segmento es su propia parada de tabulación, igual que ya funciona un input de fecha nativo de varias partes, así que el uso por teclado no necesita nada más que Tab y las flechas documentadas arriba: más <code>Alt+Flecha-abajo</code> para abrir el desplegable sin llegar hasta su botón, y las flechas/Inicio/Fin/Escape ya provistas por <code>@zag-js/select</code> una vez adentro de la lista.',
    "timeFieldPage.test1": "Monta una sola vez y nombra el grupo a partir del label autorado.",
    "timeFieldPage.test2": "Deriva los segmentos del locale, no del markup.",
    "timeFieldPage.test3": "Empieza vacío, con placeholders en vez de una hora inventada.",
  },
  en: {
    "demo.timeField.label": "Departure",
    "demo.timeField.forced24Label": "Arrival (24-hour)",

    "timeFieldPage.description": "A segmented time field with a built-in dropdown: hour, minute, and AM/PM as editable parts, plus a list of preset times, all keyboard-operable.",
    "timeFieldPage.lede":
      "A field for a local clock time, no date, no timezone. Hour, minute, and (in a 12-hour locale) AM/PM are three independent editable segments in a single field, instead of the native <code>&lt;input type=\"time\"&gt;</code>'s own chrome, which differs enough between Chrome, Firefox, and Safari that it cannot be styled or trusted to look the same twice. There is no <code>@zag-js/time-picker</code> machine for those segments, so that part is hand-rolled state, like Slider and Segmented: but there IS a dropdown, always present, a plain arrow-key-navigable list (no search box: too much machine for a short, ordered list). Two things were tried and dropped on the way there: a wheel picker (neither simpler nor more accessible than the segments themselves) and a searchable Combobox-style list (too much machine for a short list).",
    "timeFieldPage.contractBody":
      "The order of the segments and the separator between them are read from <code>Intl.DateTimeFormat</code>'s own <code>formatToParts</code>, never assumed: some locales put the period of day before the hour, and the separator is not always <code>\":\"</code>. The public value stays the canonical <code>HH:mm</code> string, the same shape a plain <code>&lt;input type=\"time\"&gt;</code> sends, carried in a hidden input, so a form behind TimeField never has to parse a locale-dependent string. React keeps it as component state (<code>value</code>/<code>defaultValue</code>, an <code>onValueChange</code> callback). Vanilla hydrates the authored <code>data-sk-time-field</code>: the consumer only authors the root and its label, and the component generates the segments from <code>data-locale</code>.",
    "timeFieldPage.editTitle": "Editing a segment",
    "timeFieldPage.editBody":
      'Typing a digit fills the focused segment and advances as soon as no other digit could keep it valid: typing <kbd class="sk-kbd">1</kbd> in a 12-hour field\'s hour segment briefly waits for a possible second digit (<code>10</code>–<code>12</code>), typing <kbd class="sk-kbd">9</kbd> advances immediately, because no second digit could follow it and stay ≤ 12. The up/down arrows raise or lower the value and wrap at the ends; <kbd class="sk-kbd">Backspace</kbd> clears the segment; <kbd class="sk-kbd">←</kbd>/<kbd class="sk-kbd">→</kbd> move between segments; typing the locale\'s AM/PM label\'s first letter in that segment sets it directly.',
    "timeFieldPage.forced24Title": "Forcing 24-hour form, without depending on the locale",
    "timeFieldPage.forced24Body":
      'Auto-detection (<code>getHourCycle</code>) reads <code>Intl.DateTimeFormat(locale, {hour:"numeric"}).resolvedOptions().hourCycle</code>, and that value turned out to be inconsistent across engines: the same locale string (<code>es</code>/<code>es-AR</code>) resolves to opposite cycles in Node and in a real Chromium. Since the hour segment\'s own max comes straight from that cycle, a wrong guess did not just mislabel the hour: it advanced focus too early on an ambiguous first digit (a "2", which could still become "22"). The <code>hourCycle</code> option overrides the guess when a guaranteed 24-hour field is what you actually need, regardless of browser.',
    "timeFieldPage.nativeTitle": "If you only need the platform's own picker",
    "timeFieldPage.nativeBody":
      'A plain <code>&lt;input type="time"&gt;</code> still works, needs no CSS or JavaScript, and comes with the operating system\'s own keyboard and picker for free. Move up to TimeField only once that picker\'s cross-browser inconsistency, or the total absence of styling hooks, actually costs you something: the same decision DatePicker makes against a plain <code>type="date"</code>.',
    "timeFieldPage.nativeLabel": "Native time input",
    "timeFieldPage.optionsTitle": "The dropdown, at another step",
    "timeFieldPage.optionsBody":
      'The clock button paints INSIDE <code>.sk-time-field__control</code>: one bordered box, the same anatomy Combobox\'s own control already has for its own trailing buttons: and opens a plain, search-free list, navigable with arrow keys: <code>@zag-js/select</code> drives that machine directly (the same one <code>Select</code> uses), without mounting the full <code>Select</code> component, which carries its own visible trigger and would have meant two clicks to reach the list. The <code>optionsStep</code> option (30 minutes by default, 48 rows) decides how far apart each row sits; <code>Alt+ArrowDown</code> from any segment opens it without tabbing there first, the same key that already opens a native <code>&lt;select&gt;</code>.',
    "timeFieldPage.optionsQuarterHourTitle": "Every 15 minutes",
    "timeFieldPage.a11yBody":
      "Every segment is a <code>role=\"spinbutton\"</code> inside a <code>role=\"group\"</code> named by the field's label: <code>aria-valuenow</code>/<code>aria-valuetext</code> carry its current value (a friendly placeholder like \"hh\" before anything is set, never an empty string), and <code>aria-valuemin</code>/<code>aria-valuemax</code> carry its real range: 1–12 for an hour segment in a 12-hour locale, 0–23 in a 24-hour one. Every segment is its own tab stop, the same way a native multi-part date input already works, so keyboard use needs nothing beyond Tab and the arrows documented above: plus <code>Alt+ArrowDown</code> to open the dropdown without reaching its own button, and the arrows/Home/End/Escape <code>@zag-js/select</code> already provides once inside the list.",
    "timeFieldPage.test1": "Mounts once and names the group from the authored label.",
    "timeFieldPage.test2": "Derives the segments from the locale, not from the markup.",
    "timeFieldPage.test3": "Starts empty, with placeholders instead of a made-up time.",
  },
} as const;
