import type { UsageTree } from "@skryensya/core/usage-tree";
import type { Translate } from "../i18n";
import { anatomyCanvas, anatomyHints, namePart } from "./annotation-parts";
import peaksByPiece from "./audio-peaks.json";

type UIKey = Parameters<Translate>[0];

/*
 * AUDIO PLAYER DEMOS. Three short pieces and their covers, generated by `scripts/generate-demo-audio.ts` and hosted under
 * `public/audio/` so the demos and the gates work offline and carry no licence line. The PEAKS are measured from the very
 * samples that script writes, so the waveform is the file's, not a drawing of a wave.
 */

const k = (name: string) => `demo.audioPlayer.${name}` as UIKey;

type Piece = "morning-light" | "slow-tide" | "paper-planes";

const piece = (name: Piece) => ({
  src: `/audio/${name}.wav`,
  cover: `/audio/${name}.svg`,
  peaks: (peaksByPiece as Record<Piece, number[]>)[name].join(" "),
});

const words = (t: Translate) => ({
  label: t(k("label")),
  playLabel: t(k("playLabel")),
  pauseLabel: t(k("pauseLabel")),
  replayLabel: t(k("replayLabel")),
  muteLabel: t(k("muteLabel")),
  unmuteLabel: t(k("unmuteLabel")),
  seekLabel: t(k("seekLabel")),
  volumeLabel: t(k("volumeLabel")),
  speedLabel: t(k("speedLabel")),
  previousLabel: t(k("previousLabel")),
  nextLabel: t(k("nextLabel")),
  tracksLabel: t(k("tracksLabel")),
  timeLabel: t(k("timeLabel")),
});

const ARTIST = "Skryensya Demo";

const single = (t: Translate, name: Piece, title: string, options: Record<string, string | number | boolean> = {}, rootStyle?: string): UsageTree => ({
  contract: "audio-player",
  signature: "AudioPlayer",
  options: { ...words(t), ...piece(name), title, artist: ARTIST, ...options },
  ...(rootStyle ? { attrs: { style: rootStyle } } : {}),
});

/** 1. The strip as it is: a cover, the words, a waveform, the controls. */
export const audioPlayerTree = (t: Translate): UsageTree => single(t, "morning-light", "Morning Light", {}, "max-inline-size: 36rem;");

/** The three demo pieces as a list. */
const tracksOf = (): UsageTree["slots"] => ({
  tracks: (
    [
      ["morning-light", "Morning Light", 20],
      ["slow-tide", "Slow Tide", 20],
      ["paper-planes", "Paper Planes", 20],
    ] as const
  ).map(([name, title, duration]) => ({
    options: { ...piece(name), duration },
    slots: { title, artist: ARTIST },
  })),
});

/** 2. The card with a list: the cover, the words and the controls in one column, and the tracks under them. Previous and next appear with the list. */
export const audioPlayerCardTree = (t: Translate): UsageTree => ({
  contract: "audio-player",
  signature: "AudioPlayer",
  options: { ...words(t), label: t(k("playlistLabel")), variant: "card" },
  slots: tracksOf(),
});

/** 3. A list in the strip: one player, three tracks, the next one starting when one ends. */
export const audioPlayerPlaylistTree = (t: Translate): UsageTree => ({
  contract: "audio-player",
  signature: "AudioPlayer",
  options: { ...words(t), label: t(k("playlistLabel")) },
  attrs: { style: "max-inline-size: 36rem;" },
  slots: tracksOf(),
});

/** 0. The least a sound needs: a play button, the bar and the time. */
export const audioPlayerMinimalTree = (t: Translate): UsageTree => ({
  contract: "audio-player",
  signature: "AudioPlayerMinimal",
  options: {
    label: t(k("label")),
    src: piece("morning-light").src,
    title: "Morning Light",
    playLabel: t(k("playLabel")),
    pauseLabel: t(k("pauseLabel")),
    replayLabel: t(k("replayLabel")),
    seekLabel: t(k("seekLabel")),
    timeLabel: t(k("timeLabel")),
  },
  attrs: { style: "max-inline-size: 28rem;" },
});

/* The anatomy's specimen: one piece with everything a single sound can carry. */
export const audioPlayerAnatomyCss = `.sk-annotated-figure {
  --sk-annotation-font-family: var(--font-family-code);
}

.sk-annotated__subject > .sk-audio-player {
  inline-size: min(100%, 34rem);
}
`;

export const audioPlayerAnatomyTree = (t: Translate): UsageTree => ({
  contract: "annotation",
  signature: "Annotated",
  options: { ...anatomyCanvas(t), label: t("audioPlayerPage.anatomyLabel"), inert: true },
  slots: {
    ...anatomyHints(t),
    subject: single(t, "morning-light", "Morning Light"),
    items: [
      namePart(".sk-audio-player", "block-start", { mark: "bracket" }),
      namePart(".sk-audio-player__cover", "inline-start", { ringPlacement: "offset", ringDistance: 2 }),
      namePart(".sk-audio-player__meta", "block-start", { ringPlacement: "offset", ringDistance: 2 }),
      namePart(".sk-audio-player__seek", "inline-end", { ringPlacement: "offset", ringDistance: 2 }),
      namePart(".sk-audio-player__bar", "block-end", { mark: "bracket" }),
      namePart(".sk-audio-player__volume", "inline-start", { ringPlacement: "offset", ringDistance: 2 }),
      namePart(".sk-audio-player__time", "block-end", { ringPlacement: "offset", ringDistance: 2 }),
    ],
  },
});

/*
 * DO / DON'T, two pairs, one lesson each. A half is emitted as static markup and never hydrated, so nothing plays and no
 * waveform is drawn: what shows is the player at rest, which is what a reader meets before pressing anything.
 */

/** 1. Name what plays. With a title, an artist and a cover the player says what it holds; without them it is a row of buttons. */
export const audioPlayerDoNameTree = (t: Translate): UsageTree => single(t, "morning-light", "Morning Light", {}, "max-inline-size: 30rem;");

export const audioPlayerDontNameTree = (t: Translate): UsageTree => {
  const tree = single(t, "morning-light", "Morning Light", {}, "max-inline-size: 30rem;");
  const { title: _title, artist: _artist, cover: _cover, ...options } = tree.options!;
  return { ...tree, options };
};

/** 2. Room. The strip is a row of buttons and a clock; in a box too narrow for them it wraps onto itself. */
export const audioPlayerDoRoomTree = (t: Translate): UsageTree => single(t, "slow-tide", "Slow Tide", {}, "max-inline-size: 30rem;");

export const audioPlayerDontRoomTree = (t: Translate): UsageTree => single(t, "slow-tide", "Slow Tide", {}, "max-inline-size: 13rem;");
