import { avatarInitials } from "@skryensya/core/avatar";
import type { Translate } from "../i18n";
import { userSelectRoster, type UserSelectDemoUser } from "./data/user-select";

/*
 * BOTH HALVES OF THE PAGE, hand-authored rather than emitted from a `UsageTree`: UserSelect has no
 * compiled contract of its own (see `UserSelectPage.astro`'s own note), so there is no single
 * artifact to emit this markup FROM. The roster is the one thing shared (`data/user-select.ts`), the
 * same precedent `demos/select.ts` sets with `planItems`.
 *
 * Every row already carries its own `.sk-avatar`, hand-built with the SAME fallback derivation
 * `Avatar`'s React binding uses (`avatarInitials`): the enhancer never re-derives it, it only clones
 * whatever the row already has.
 */

const row = (user: UserSelectDemoUser): string => `<div class="sk-select__item sk-interactive" data-sk-select-item data-value="${user.id}" data-email="${user.email}"${user.disabled ? " data-disabled" : ""}>
        <span class="sk-avatar" data-size="sm" role="img" aria-label="${user.name}" style="--sk-avatar-bg: var(--palette-${user.hue}); --sk-avatar-fg: var(--palette-white);"><span class="sk-avatar__fallback" aria-hidden="true">${avatarInitials(user.name)}</span></span>
        <span class="sk-combobox__item-copy">
          <span class="sk-select__item-text" data-sk-select-item-text>${user.name}</span>
          <span class="sk-select__item-text sk-combobox__item-description">${user.email}</span>
        </span>
        <span class="sk-select__item-indicator" data-sk-select-item-indicator aria-hidden="true"><span data-sk-icon="check" data-sk-icon-size="md"></span></span>
      </div>`;

/** The live Vanilla stage: authored rows, a search field, and nothing else generated by hand. */
export const userSelectHtml = (t: Translate, roster: readonly UserSelectDemoUser[] = userSelectRoster): string => `<div
  class="sk-select"
  data-sk-user-select
  id="assignees"
  data-value="jane"
  data-placeholder="${t("userSelectPage.placeholder")}"
  data-search-placeholder="${t("userSelectPage.searchPlaceholder")}"
>
  <div class="sk-select__control" data-sk-select-control>
    <button class="sk-select__trigger sk-anchor sk-interactive" data-sk-select-trigger type="button">
      <span class="sk-select__value" data-sk-select-value></span>
      <span class="sk-select__indicator" data-sk-select-indicator aria-hidden="true">
        <span data-state="closed"><span data-sk-icon="chevron-down" data-sk-icon-size="md"></span></span>
        <span data-state="open"><span data-sk-icon="chevron-up" data-sk-icon-size="md"></span></span>
      </span>
    </button>
  </div>
  <div class="sk-select__positioner sk-anchored" data-sk-select-positioner>
    <div class="sk-select__content" data-sk-select-content>
      <input class="sk-input" data-sk-user-select-search type="search" placeholder="${t("userSelectPage.searchPlaceholder")}" data-size="sm" />
      ${roster.map(row).join("\n      ")}
    </div>
  </div>
</div>`;

/** An empty roster: the "no users available" branch, frozen open. */
export const userSelectEmptyHtml = (t: Translate): string => `<div class="sk-select" data-sk-user-select id="assignees-empty" data-placeholder="${t("userSelectPage.placeholder")}">
  <div class="sk-select__control" data-sk-select-control>
    <button class="sk-select__trigger sk-anchor sk-interactive" data-sk-select-trigger type="button">
      <span class="sk-select__value" data-sk-select-value></span>
      <span class="sk-select__indicator" data-sk-select-indicator aria-hidden="true">
        <span data-state="closed"><span data-sk-icon="chevron-down" data-sk-icon-size="md"></span></span>
        <span data-state="open"><span data-sk-icon="chevron-up" data-sk-icon-size="md"></span></span>
      </span>
    </button>
  </div>
  <div class="sk-select__positioner sk-anchored" data-sk-select-positioner>
    <div class="sk-select__content" data-sk-select-content>
      <input class="sk-input" data-sk-user-select-search type="search" placeholder="${t("userSelectPage.searchPlaceholder")}" data-size="sm" />
    </div>
  </div>
</div>`;

export const userSelectJs = `import { initComponents } from "@skryensya/vanilla/auto";
import { mountIcons } from "@skryensya/vanilla/icon";
import { lucideIcons } from "@skryensya/icons-lucide";

mountIcons(document, lucideIcons);

await initComponents();`;

export const userSelectListen = `document
  .getElementById("assignees")
  .addEventListener("sk:userselectvaluechange", (event) => {
    console.log(event.detail.value); // ["jane", "maria"]
  });`;
