import { avatarInitials } from "@skryensya/core/avatar";
import { userSelectLabel, userSelectLabels, type UserSelectLabels } from "@skryensya/core/user-select";
import type { UsageTree } from "@skryensya/core/usage-tree";
import type { Translate, UIKey } from "../i18n";
import { userSelectRoster, type UserSelectDemoUser } from "./data/user-select";

/*
 * BOTH HALVES OF THE PAGE, hand-authored rather than emitted from a `UsageTree`: UserSelect has no
 * compiled contract of its own (see `UserSelectPage.astro`'s own note), so there is no single
 * artifact to emit this markup FROM. The roster is the one thing shared (`data/user-select.ts`), the
 * same precedent `demos/select.ts` sets with `planItems`.
 *
 * Every row already carries its own `.sk-avatar`, hand-built with the SAME fallback derivation
 * `Avatar`'s React binding uses (`avatarInitials`): the enhancer never re-derives it, it only clones
 * whatever the row already has.
 */

const row = (user: UserSelectDemoUser): string => `<div class="sk-select__item sk-interactive" data-sk-select-item data-value="${user.id}"${user.disabled ? " data-disabled" : ""}>
        <span class="sk-inline" data-align="center" data-gap="sm" data-wrap="false">
        <span class="sk-avatar" data-size="sm" data-appearance="plain" role="img" aria-label="${user.name}" aria-hidden="true" style="--sk-avatar-bg: var(--palette-${user.hue}); --sk-avatar-fg: var(--palette-white);"><span class="sk-avatar__fallback" aria-hidden="true">${avatarInitials(user.name)}</span></span>
        <span class="sk-combobox__item-copy">
          <span class="sk-select__item-text" data-sk-select-item-text>${user.name}</span>
          <span class="sk-select__item-text sk-combobox__item-description">${user.email}</span>
        </span>
        </span>
      </div>`;

const labelKeys = Object.keys(userSelectLabels) as (keyof UserSelectLabels)[];

/** The page's strings for UserSelect in `t`'s locale, one message per key (`userSelectPage.label.*`). */
export const userSelectDemoLabels = (t: Translate): UserSelectLabels =>
  Object.fromEntries(labelKeys.map((key) => [key, t(`userSelectPage.label.${key}` as UIKey)])) as UserSelectLabels;

const kebab = (key: string) => key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const attrEscape = (value: string) => value.replaceAll("&", "&amp;").replaceAll('"', "&quot;");

/*
 * Only the strings that differ from the defaults become attributes: the English page authors none,
 * the Spanish one authors every sentence, which is exactly what localizing it takes.
 */
const labelAttrs = (t: Translate): string => {
  const labels = userSelectDemoLabels(t);
  return labelKeys
    .filter((key) => labels[key] !== userSelectLabels[key])
    .map((key) => {
      const name = key === "term" || key === "placeholder" || key === "searchPlaceholder" ? kebab(key) : `${kebab(key)}-label`;
      return `\n  data-${name}="${attrEscape(labels[key])}"`;
    })
    .join("");
};

const searchPlaceholder = (t: Translate) => attrEscape(userSelectLabel(userSelectDemoLabels(t), "searchPlaceholder"));

/** The live Vanilla stage: authored rows, a search field, and nothing else generated by hand. */
export const userSelectHtml = (t: Translate, roster: readonly UserSelectDemoUser[] = userSelectRoster): string => `<div
  class="sk-select"
  data-sk-user-select
  data-variant="ghost"
  id="assignees"
  data-value="jane"${labelAttrs(t)}
>
  <div class="sk-select__control" data-sk-select-control>
    <button class="sk-select__trigger sk-anchor sk-interactive" data-sk-select-trigger type="button">
      <span class="sk-select__value" data-sk-select-value></span>
      <span class="sk-select__indicator" data-sk-select-indicator aria-hidden="true">
        <span data-state="closed"><span data-sk-icon="chevron-down" data-sk-icon-size="md"></span></span>
        <span data-state="open"><span data-sk-icon="chevron-up" data-sk-icon-size="md"></span></span>
      </span>
    </button>
  </div>
  <div class="sk-select__positioner sk-anchored" data-sk-select-positioner>
    <div class="sk-select__content" data-sk-select-content>
      <input class="sk-input" data-sk-user-select-search type="search" placeholder="${searchPlaceholder(t)}" data-size="sm" />
      ${roster.map(row).join("\n      ")}
    </div>
  </div>
</div>`;

/** An empty roster: the "no users available" branch, frozen open. */
export const userSelectEmptyHtml = (t: Translate): string => `<div class="sk-select" data-sk-user-select data-variant="ghost" id="assignees-empty"${labelAttrs(t)}>
  <div class="sk-select__control" data-sk-select-control>
    <button class="sk-select__trigger sk-anchor sk-interactive" data-sk-select-trigger type="button">
      <span class="sk-select__value" data-sk-select-value></span>
      <span class="sk-select__indicator" data-sk-select-indicator aria-hidden="true">
        <span data-state="closed"><span data-sk-icon="chevron-down" data-sk-icon-size="md"></span></span>
        <span data-state="open"><span data-sk-icon="chevron-up" data-sk-icon-size="md"></span></span>
      </span>
    </button>
  </div>
  <div class="sk-select__positioner sk-anchored" data-sk-select-positioner>
    <div class="sk-select__content" data-sk-select-content>
      <input class="sk-input" data-sk-user-select-search type="search" placeholder="${searchPlaceholder(t)}" data-size="sm" />
    </div>
  </div>
</div>`;

/* Mounted by the auto-loader like every other family: UserSelect is in its registry now. */
export const userSelectJs = `import { initComponents } from "@skryensya/vanilla/auto";
import { mountIcons } from "@skryensya/vanilla/icon";
import { lucideIcons } from "@skryensya/icons-lucide";

mountIcons(document, lucideIcons);
await initComponents();`;

export const userSelectListen = `document
  .getElementById("assignees")
  .addEventListener("sk:userselectvaluechange", (event) => {
    console.log(event.detail.value); // ["jane", "maria"]
  });`;

/*
 * THE ANATOMY: the enhanced DOM, frozen open, drawn in flow. Written by hand rather than emitted from
 * a tree because the specimen needs the list OPEN and in flow, and the rows in their colors; the
 * shape is `userSelectContract`'s template. The root deliberately does NOT
 * carry `data-sk-user-select`: the preview frame mounts anything that does, and a specimen must not
 * become a live picker.
 */
const anatomyAvatar = (user: UserSelectDemoUser): string =>
  `<span class="sk-avatar" data-size="sm" style="--sk-avatar-bg: var(--palette-${user.hue}); --sk-avatar-fg: var(--palette-white);"><span class="sk-avatar__fallback">${avatarInitials(user.name)}</span></span>`;

const anatomyRow = (user: UserSelectDemoUser, checked: boolean): string => `<div class="sk-select__item sk-interactive" role="option" aria-selected="${checked}" data-state="${checked ? "checked" : "unchecked"}">
                <span class="sk-checkbox" data-sk-user-select-check aria-hidden="true"><span class="sk-checkbox__control"><span class="sk-checkbox__indicator" data-state="checked"><span data-sk-icon="check" data-sk-icon-size="sm"></span></span></span></span>
                <span class="sk-inline" data-align="center" data-gap="sm" data-wrap="false">
                  ${anatomyAvatar(user)}
                  <span class="sk-combobox__item-copy">
                    <span class="sk-select__item-text">${user.name}</span>
                    <span class="sk-select__item-text sk-combobox__item-description">${user.email}</span>
                  </span>
                </span>
              </div>`;

/*
 * THE SAME PICKER AS A USAGE TREE, the contract's own shape: what the stories and the MCP examples
 * are built from. The page's live stage stays hand-authored only for the colored avatars, which a
 * tree cannot express; the structure is the same.
 */
export const userSelectTree = (t: Translate): UsageTree => {
  const labels = userSelectDemoLabels(t);
  const options: Record<string, string> = { name: "assignees", value: "jane" };
  // Only what the locale changes: the English page's tree carries none of these.
  if (labels.term !== userSelectLabels.term) options.term = labels.term;
  for (const [option, key] of [
    ["placeholder", "placeholder"],
    ["searchPlaceholder", "searchPlaceholder"],
    ["unselectedLabel", "unselected"],
  ] as const) {
    if (labels[key] !== userSelectLabels[key]) options[option] = userSelectLabel(labels, key);
  }
  return {
    contract: "user-select",
    signature: "UserSelect",
    options,
    slots: {
      items: userSelectRoster.map((user) => ({
        options: { id: user.id, ...(user.disabled ? { disabled: true } : {}) },
        slots: { name: user.name, initials: avatarInitials(user.name), email: user.email },
      })),
    },
  };
};

/** Four people chosen at once: the trigger stacks them as an AvatarGroup. */
export const userSelectMultipleTree = (t: Translate): UsageTree => {
  const tree = userSelectTree(t);
  return { ...tree, options: { ...tree.options, name: "assignees-multiple", value: "jane maria marco john" } };
};

/** The roster still arriving: open it and the list shows a Loader and the `loading` string. */
export const userSelectLoadingTree = (t: Translate): UsageTree => {
  const tree = userSelectTree(t);
  return { ...tree, options: { ...tree.options, name: "assignees-loading", loading: true } };
};
