/*
 * Generates the Lucide set from the library.
 *
 * WHY THERE IS CODEGEN HERE AND NOT IN THE MANIFEST. Decision 15 rejected the manifest generator
 * because the allowlist reimplements the bundler's tree-shaking: delete it and the consumer writes an
 * object literal, with no complexity reappearing. This generator is a different thing: it converts the
 * library's format to IconData. Delete it and complexity DOES reappear: the consumer parses SVG at
 * runtime, or ties itself to `?raw`, which is Vite's and not the ecosystem's. Same test, falling the
 * other way.
 *
 * And the result pays twice: the library stays a devDependency, so the consumer's bundle receives 32
 * icons of data and ZERO Lucide runtime.
 *
 * The shell (--check, the emitted template) is shared by all three sets and lives in
 * @skryensya/core/emit-icon-set. What is left here is only what varies: the MAP, the ATTRS, the header,
 * and how ONE name resolves to geometry. Lucide is the data-shaped adapter: the library hands back
 * nodes, not `.svg` files, so its `resolve` serializes the children instead of reading and extracting a
 * file (which is what Phosphor and Material do).
 */
import { generateIconSet } from "@skryensya/core/emit-icon-set";
import { icons } from "lucide";

/* System role → Lucide's name. This table is the only part a human maintains, and it is where you see
 * that the role is ours and the name is theirs: `delete` is their `Trash2`. */
const MAP = {
  "chevron-up": "ChevronUp",
  "chevron-down": "ChevronDown",
  "chevron-left": "ChevronLeft",
  "chevron-right": "ChevronRight",
  "arrow-up": "ArrowUp",
  "vote-up": "ArrowBigUp",
  "vote-down": "ArrowBigDown",
  "arrow-down": "ArrowDown",
  "arrow-left": "ArrowLeft",
  "arrow-right": "ArrowRight",
  "external-link": "ExternalLink",
  add: "Plus",
  remove: "Minus",
  close: "X",
  check: "Check",
  search: "Search",
  edit: "Pencil",
  delete: "Trash2",
  copy: "Copy",
  filter: "Funnel",
  refresh: "RefreshCw",
  "zoom-out": "ZoomOut",
  more: "Ellipsis",
  menu: "Menu",
  info: "Info",
  bold: "Bold",
  italic: "Italic",
  link: "Link",
  success: "CircleCheck",
  warning: "TriangleAlert",
  danger: "CircleX",
  calendar: "Calendar",
  clock: "Clock",
  upload: "Upload",
  download: "Download",
  file: "File",
  folder: "Folder",
  settings: "Settings",
  user: "User",
  language: "Languages",
  visibility: "Eye",
  "visibility-off": "EyeOff",
  "mode-system": "Monitor",
  "mode-light": "Sun",
  "mode-dark": "Moon",
  "screen-desktop": "Monitor",
  "screen-tablet": "Tablet",
  "screen-mobile": "Smartphone",
};

/* Lucide's `<svg>` defaults. They go in attrs and not in the CSS because a CSS declaration beats a
 * presentation attribute: a `fill: currentColor` in patterns/icon.css would turn this whole set solid,
 * and it is an outline set. */
const ATTRS = {
  fill: "none",
  stroke: "currentColor",
  "stroke-width": "2",
  "stroke-linecap": "round",
  "stroke-linejoin": "round",
};

const HEADER = `/*
 * GENERATED by scripts/generate.ts, do not edit by hand.
 *
 * Lucide geometry (ISC), redistributed under its license. See LICENSE-lucide.
 */`;

/** Lucide hands back `[["path", {d}], ["circle", {...}]]`, data, not markup. We serialize the children. */
const toBody = (nodes: (typeof icons)[keyof typeof icons]) =>
  nodes
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(" ")} />`)
    .join("");

/** Lucide's adapter: the geometry is data, and the library's viewBox is always `0 0 24 24`. */
const resolve = (name: string, role: string) => {
  const nodes = icons[name as keyof typeof icons];
  if (!nodes) throw new Error(`Lucide no tiene "${name}" (rol "${role}"), ¿se renombró en un upgrade?`);
  return { viewBox: "0 0 24 24", body: toBody(nodes) };
};

generateIconSet({ dir: import.meta.dirname, label: "lucide", map: MAP, attrs: ATTRS, header: HEADER, resolve });
