/*
 * Batteries-included CSS bundle.
 *
 * The Sass path stays the authoring surface: a consumer with a bundler imports the one token entrypoint
 * and any optional dimensions or component hooks. This bundle is the no-toolchain path:
 *
 *   <link rel="stylesheet" href="@skryensya/core/skryensya.css">
 *
 * `primitives.scss` already includes the one root ramp set, so the bundle needs no brand selection or
 * attribute. Generated output is never committed; it is published via package.json `files`.
 */
import { compileString } from "sass";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const CSS = join(ROOT, "css");
const DIST = join(ROOT, "dist");

// Token tiers already include root ramps; optional dimensions follow. The layer statement fixes priority
// regardless of source order.
//
// EVERY dimension ships here, radius AND accent reach. The bundle is the no-toolchain path, so a
// dimension missing from this list is a dimension that does not exist for that consumer: `data-radius`
// worked and `data-accent` was silently inert, an attribute the documentation promises and the
// stylesheet never declares. The Sass path stays opt-in per dimension; the bundle is batteries-included
// by definition, and an unused `[data-accent]` block costs seven declarations.
const ENTRY = `
@use "primitives";
@use "semantic";
@use "modes/hc";
@use "dimensions/radius";
@use "dimensions/accent";
@layer primitives, semantic, components, overrides;
`;

const tokensCss = compileString(ENTRY, { loadPaths: [CSS], style: "expanded" }).css;

const readDir = (sub) =>
  readdirSync(join(CSS, sub))
    .filter((f) => f.endsWith(".css"))
    .sort()
    .map((f) => ({ f, css: readFileSync(join(CSS, sub, f), "utf8") }));

const patterns = readDir("patterns");
const components = readDir("components");

// One @charset, at the very top, strip any that the parts carry in.
const strip = (css) => css.replace(/@charset[^;]*;\s*/gi, "");
const section = (label, items) =>
  items.map(({ f, css }) => `/* ── ${label}/${f} ── */\n${strip(css)}`).join("\n\n");

const out =
  `@charset "UTF-8";\n` +
  `/* @skryensya/core, batteries-included bundle. Generated by scripts/build-css.mjs (ADR-22). */\n\n` +
  strip(tokensCss) +
  `\n\n` +
  section("patterns", patterns) +
  `\n\n` +
  section("components", components) +
  `\n`;

mkdirSync(DIST, { recursive: true });
writeFileSync(join(DIST, "skryensya.css"), out);

console.log(
  `✓ dist/skryensya.css, ${(out.length / 1024).toFixed(1)} kB ` +
    `(tokens + ${patterns.length} patterns + ${components.length} components)`,
);
