/*
 * The no-toolchain path, two ways: one batteries-included bundle, or tokens plus only the
 * component/pattern CSS a page actually links. The Sass path stays the authoring surface AND the
 * a-la-carte path for a bundler-aware consumer: `@use "@skryensya/core/tokens"` plus whichever
 * `components/*.css` or `patterns/*.css` it imports. This script serves the reader with no bundler:
 *
 *   <link rel="stylesheet" href="@skryensya/core/skryensya.css">                  batteries included
 *   <link rel="stylesheet" href="@skryensya/core/tokens.css">                     tokens only, then
 *   <link rel="stylesheet" href="@skryensya/core/components/button.css">          pick what you use
 *
 * `components/*.css` and `patterns/*.css` already declare their own cross-file dependencies via
 * native `@import url(...)` (calendar imports button, layout imports box/wrapper/image-frame, …), so
 * linking just the files a page uses pulls in exactly what those files need — nothing more. Every
 * generated file here is minified: the reader of a linked stylesheet edits their own CSS, not this
 * one, so there is nothing gained by shipping it expanded. `primitives.scss` already includes the one
 * root ramp set, so the bundle needs no brand selection or attribute. Generated output is never
 * committed; it is published via package.json `files`.
 */
import { compile, compileString } from "sass";
import { transform } from "lightningcss";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const CSS = join(ROOT, "css");
const DIST = join(ROOT, "dist");

/** Minifies compiled CSS. No `targets`: this ships modern syntax (oklch, color-mix, cascade
 * layers, `::scroll-marker`) as-authored rather than downleveling it for older engines. */
const minify = (code, filename) =>
  transform({ filename, code: Buffer.from(code), minify: true }).code;

/** Writes a minified file under `dist/`, creating parent directories as needed. */
function writeDist(relPath, css, filename) {
  const out = join(DIST, relPath);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, minify(css, filename));
  return out;
}

// Token tiers already include root ramps; optional dimensions follow. The layer statement fixes priority
// regardless of source order.
//
// EVERY dimension ships here, radius, accent reach AND press scale. The bundle is the no-toolchain
// path, so a dimension missing from this list is a dimension that does not exist for that consumer:
// `data-radius` worked and `data-accent` was silently inert, an attribute the documentation promises
// and the stylesheet never declares. The Sass path stays opt-in per dimension; the bundle is
// batteries-included by definition, and an unused `[data-press-scale]` block costs one declaration.
const ENTRY = `
@use "primitives";
@use "semantic";
@use "modes/hc";
@use "dimensions/radius";
@use "dimensions/accent";
@use "dimensions/press-scale";
@layer primitives, semantic, components, overrides;
`;

const tokensCss = compileString(ENTRY, { loadPaths: [CSS], style: "expanded" }).css;

const readDir = (sub) =>
  readdirSync(join(CSS, sub))
    .filter((f) => f.endsWith(".css"))
    .sort()
    .map((f) => ({ f, css: readFileSync(join(CSS, sub, f), "utf8") }));

const patterns = readDir("patterns");
const components = readDir("components");

// One @charset, at the very top, strip any that the parts carry in. Every part's own
// `@import url("./sibling.css")` also gets stripped here: the bundle already inlines every pattern
// and every component unconditionally, so the imported file is always present in full elsewhere in
// this same file, making the `@import` pure dead weight — and, worse, invalid CSS in this position
// (an `@import` may only precede other rules, which this bundle's tokens section already emitted).
const strip = (css) =>
  css.replace(/@charset[^;]*;\s*/gi, "").replace(/^@import\s+url\([^)]*\)\s*;\s*$/gim, "");
const section = (label, items) =>
  items.map(({ f, css }) => `/* ── ${label}/${f} ── */\n${strip(css)}`).join("\n\n");

const bundle =
  `@charset "UTF-8";\n` +
  `/* @skryensya/core, batteries-included bundle. Generated by scripts/build-css.mjs (ADR-22). */\n\n` +
  strip(tokensCss) +
  `\n\n` +
  section("patterns", patterns) +
  `\n\n` +
  section("components", components) +
  `\n`;

mkdirSync(DIST, { recursive: true });
const results = [];

results.push([
  "skryensya.css",
  writeDist("skryensya.css", bundle, "skryensya.css"),
  `tokens + ${patterns.length} patterns + ${components.length} components`,
]);

// The foundation alone, no patterns or components: everything a consumer needs before it links even
// one component — same ENTRY as the full bundle above (so it stays in lockstep with it), just without
// the two `section(...)` calls that append patterns and components. Built for the docs playground
// sandbox (`apps/docs/scripts/build-sandbox-bundles.mjs`), which links this once and then only the
// component CSS a given example actually uses, instead of shipping every component's CSS unconditionally.
const foundationCss = `@charset "UTF-8";\n` + strip(tokensCss) + `\n`;
results.push([
  "foundation.css",
  writeDist("foundation.css", foundationCss, "foundation.css"),
  "tokens + modes/hc + dimensions/radius + dimensions/accent + dimensions/press-scale, no patterns or components",
]);

// The a-la-carte path: tokens compiled standalone, so a page can link just the components it uses
// instead of the whole bundle. Primitives + semantic only, matching what a bare `@use
// "@skryensya/core/tokens"` gives a Sass consumer before it opts into modes/dimensions. The three
// patterns `tokens.scss` ships in base — state-layer, visually-hidden, icon; never opt-in, see that
// file's own header — are inlined here rather than `@import`-ed: their source `@import
// url("./patterns/…")` is only valid relative to css/, and this file is published from dist/.
const TOKENS_ENTRY = `
@use "primitives";
@use "semantic";
@layer primitives, semantic, components, overrides;
`;
const BASE_PATTERNS = ["state-layer.css", "visually-hidden.css", "icon.css"];
const tokensOnlyCss = compileString(TOKENS_ENTRY, { loadPaths: [CSS], style: "expanded" }).css;
const tokensOut =
  `@charset "UTF-8";\n` +
  strip(tokensOnlyCss) +
  `\n\n` +
  section("patterns", patterns.filter((p) => BASE_PATTERNS.includes(p.f)));

results.push([
  "tokens.css",
  writeDist("tokens.css", tokensOut, "tokens.css"),
  "primitives + semantic + the always-on patterns",
]);

for (const [rel, label] of [
  ["modes/hc.scss", "modes/hc.css"],
  ["dimensions/radius.scss", "dimensions/radius.css"],
  ["dimensions/accent.scss", "dimensions/accent.css"],
  ["dimensions/press-scale.scss", "dimensions/press-scale.css"],
]) {
  const css = compile(join(CSS, rel), { loadPaths: [CSS], style: "expanded" }).css;
  results.push([label, writeDist(label, css, label), "optional, opt in like the Sass path"]);
}

for (const [name, path, note] of results) {
  const kb = (readFileSync(path).length / 1024).toFixed(1);
  console.log(`✓ dist/${name}, ${kb} kB (${note})`);
}
