/*
 * The shared shell every icon-set generator was copy-pasting.
 *
 * ADR-19 keeps one codegen per set, SVG/library format → IconData, because that conversion passes
 * the deletion test the rejected manifest generator failed. What it does NOT ask for is three copies of
 * the SAME shell around it: the `--check`/write branch, the emitted `out` template, and (for the two
 * SVG-file sets) the `<svg>` body extraction were byte-identical across icons-phosphor and
 * icons-material, and nearly so in icons-lucide. That shell is the duplication, not the conversion.
 *
 * So the shell lives here and each set supplies only what genuinely varies: its role→vendor `map`, its
 * presentation `attrs`, its licence `header`, and a `resolve(vendorName, role) → { viewBox, body }`
 * adapter. Two SVG-file adapters (Phosphor, Material) already justify that seam; Lucide is the third,
 * data-shaped adapter proving it. `resolve` runs in the CALLER's module on purpose, `import.meta.resolve`
 * must see the set's own devDependency, which core cannot.
 *
 * The emitted output is byte-for-byte what the three hand-written generators produced, so the committed
 * `src/generated/set.ts` files and their `--check` gate keep passing unchanged.
 */

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export interface IconGeometry {
  viewBox: string;
  body: string;
}

export interface IconSetSource {
  map: Record<string, string>;
  attrs: Record<string, string>;
  header: string;
  resolve: (vendorName: string, role: string) => IconGeometry;
}

export interface IconSetConfig extends IconSetSource {
  dir: string;
  label: string;
  argv?: string[];
}

/**
 * Pull the viewBox and inner children out of one `<svg>…</svg>` asset. The binding writes the root
 * `<svg>`; the set contributes only what goes inside. Shared by every set whose library ships `.svg`
 * files rather than data (Phosphor, Material), it was identical in both.
 */
export function extractSvgBody(svg: string, name: string): IconGeometry {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${name}: the asset does not declare a viewBox`);
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();
  if (!body) throw new Error(`${name}: the asset was left with no body`);
  return { viewBox, body };
}

/** Build the `set.ts` source for one set. Pure: no fs, no process, just the string. */
export function buildSetSource({ map, attrs, header, resolve }: IconSetSource) {
  const entries = Object.entries(map).map(([role, name]) => {
    const { viewBox, body } = resolve(name, role);
    return `  ${JSON.stringify(role)}: { viewBox: ${JSON.stringify(viewBox)}, attrs: ATTRS, body: ${JSON.stringify(body)} },`;
  });

  return `${header}
import type { IconData } from "@skryensya/core/icon";

const ATTRS = ${JSON.stringify(attrs)} as const;

export const generated = {
${entries.join("\n")}
} satisfies Record<string, IconData>;
`;
}

const toSvgImage = ({ viewBox, body }: IconGeometry, attrs: Record<string, string>, color: string) => {
  const presentation = Object.entries(attrs)
    .map(([name, value]) => `${name}="${value === "currentColor" ? color : value}"`)
    .join(" ");
  const paintedBody = body.replaceAll("currentColor", color);
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" ` +
    `viewBox="${viewBox}" style="color-scheme:light dark" ${presentation}>${paintedBody}</svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
};

/**
 * Bind the chosen set's chevrons to Carousel's native `::scroll-button()` controls. Those
 * pseudo-elements cannot contain DOM icon placeholders, so the set supplies SVG images through the
 * component's styling hooks. System colors keep the isolated SVG images legible in every mode and
 * forced colors without moving vendor geometry into Core.
 */
export function buildCarouselIconCss({ label, map, attrs, resolve }: Pick<IconSetConfig, "label" | "map" | "attrs" | "resolve">) {
  const resolveRole = (role: string) => {
    const vendorName = map[role];
    if (!vendorName) throw new Error(`${label}: the required role "${role}" is missing`);
    return resolve(vendorName, role);
  };
  const previous = resolveRole("chevron-left");
  const next = resolveRole("chevron-right");

  return `/*
 * GENERATED by scripts/generate.ts, do not edit by hand.
 *
 * ${label} binds its chevrons to Carousel's native scroll buttons.
 */
@layer overrides {
  .sk-carousel {
    --sk-carousel-native-previous-icon: ${toSvgImage(previous, attrs, "CanvasText")};
    --sk-carousel-native-next-icon: ${toSvgImage(next, attrs, "CanvasText")};
    --sk-carousel-native-previous-disabled-icon: ${toSvgImage(previous, attrs, "GrayText")};
    --sk-carousel-native-next-disabled-icon: ${toSvgImage(next, attrs, "GrayText")};
  }
}
`;
}

/**
 * Bind the chosen set's chevrons and check to the native select's `::picker-icon` and `::checkmark`. A `<select>` cannot hold the
 * kit's icon placeholder in every browser and binding (React 19 rejects a `<button>` inside it), so
 * the set paints the pseudo-element itself, as a MASK in `currentColor`: the glyph is the same one
 * `Select`'s own trigger draws, and it follows the control's text colour through hover, disabled
 * and dark mode. Without this sheet the browser's own picker icon stays, which is the right fallback
 * for a control whose whole point is the platform.
 */
export function buildSelectIconCss({ label, map, attrs, resolve }: Pick<IconSetConfig, "label" | "map" | "attrs" | "resolve">) {
  const resolveRole = (role: string) => {
    const vendorName = map[role];
    if (!vendorName) throw new Error(`${label}: the required role "${role}" is missing`);
    return resolve(vendorName, role);
  };
  const closed = resolveRole("chevron-down");
  const open = resolveRole("chevron-up");
  const check = resolveRole("check");

  return `/*
 * GENERATED by scripts/generate.ts, do not edit by hand.
 *
 * ${label} binds its chevrons and check to the native select's picker icon and checkmark.
 */
@layer overrides {
  @supports (appearance: base-select) and selector(select::picker(select)) {
    .sk-select-native::picker-icon {
      content: "";
      background: currentColor;
      mask: ${toSvgImage(closed, attrs, "black")} center / contain no-repeat;
    }

    .sk-select-native:open::picker-icon {
      mask-image: ${toSvgImage(open, attrs, "black")};
    }

    .sk-select-native option::checkmark {
      content: "";
      background: currentColor;
      mask: ${toSvgImage(check, attrs, "black")} center / contain no-repeat;
    }
  }
}
`;
}

/**
 * The generator CLI shared by all three sets. Writes the stable role data plus the native Carousel
 * CSS adapter relative to the caller's `dir`. With `--check`, it fails if either committed artifact
 * is stale, so CI catches an upstream rename before a user ships a set with a hole.
 */
export function generateIconSet({ dir, label, map, attrs, header, resolve, argv = process.argv }: IconSetConfig) {
  const setOut = buildSetSource({ map, attrs, header, resolve });
  const carouselOut = buildCarouselIconCss({ label, map, attrs, resolve });
  const selectOut = buildSelectIconCss({ label, map, attrs, resolve });
  const count = Object.keys(map).length;
  const outputs: readonly [string, string, string][] = [
    [join(dir, "..", "src", "generated", "set.ts"), setOut, "src/generated/set.ts"],
    [join(dir, "..", "src", "carousel.css"), carouselOut, "src/carousel.css"],
    [join(dir, "..", "src", "select.css"), selectOut, "src/select.css"],
  ];

  if (argv.includes("--check")) {
    const stale = outputs.filter(([target, out]) => !existsSync(target) || readFileSync(target, "utf8") !== out);

    if (stale.length > 0) {
      console.error(`✗ ${stale.map(([, , name]) => name).join(", ")} out of date, run \`pnpm generate\``);
      process.exit(1);
    }
    console.log(`✓ ${label}: ${count} roles and the Carousel and Select adapters are up to date`);
  } else {
    for (const [target, out] of outputs) writeFileSync(target, out);
    console.log(`✓ ${label}: ${count} roles and the Carousel and Select adapters generated`);
  }
}
