/*
 * Builds the expressive avatar's bundled TILESET as ONE image: `src/expressive-avatar-atlas.ts`.
 *
 * The face used to be a sheet of 124 separate 25x25 symbols, referenced one `<use>` at a time. A tileset
 * is one image now, a grid of equal cells, and a tile is a place in it: `names[i]` lives at column
 * `i % columns`, row `floor(i / columns)`. The component shows a tile by moving the image behind a
 * 25x25 window, so changing an eye is changing a position, never loading anything.
 *
 * Run with `node scripts/generate-expressive-avatar-atlas.ts` after editing `scripts/expressive-avatar-sprite.source.ts` (the symbol sheet the atlas was cut from).
 * The colours are baked (ink and grey); the paper is left transparent, so the circle's own colour is the
 * paper, as it always was.
 */
import { writeFileSync } from "node:fs";
import {
  expressiveAvatarLeftEyeTiles,
  expressiveAvatarMouthLeftTiles,
  expressiveAvatarMouthRightTiles,
  expressiveAvatarRightEyeTiles,
  expressiveAvatarGrid,
} from "../src/expressive-avatar.ts";
import { expressiveAvatarSpriteMarkup } from "./expressive-avatar-sprite.source.ts";

const INK = "#1c1917";
const GRAY = "#cecdcc";
const TILE = 25;
const COLUMNS = 8;

/* The slot order is the layout: head and body first, then the eyes, then the mouths, then the empty tile. */
const names = [
  ...new Set([
    ...expressiveAvatarGrid.flat().filter((name) => name.startsWith("base-tile-")),
    ...Object.values(expressiveAvatarLeftEyeTiles),
    ...Object.values(expressiveAvatarRightEyeTiles),
    ...Object.values(expressiveAvatarMouthLeftTiles),
    ...Object.values(expressiveAvatarMouthRightTiles),
    "hat-empty",
  ]),
].sort((a, b) => 0); // keep insertion order

const symbols = new Map<string, string>();
for (const match of expressiveAvatarSpriteMarkup.matchAll(/<symbol id="avatar-sprite-([a-z0-9-]+)"[^>]*>(.*?)<\/symbol>/gs)) symbols.set(match[1]!, match[2]!);

const rows = Math.ceil(names.length / COLUMNS);
const cells = names.map((name, index) => {
  const body = symbols.get(name) ?? "";
  const paths = [...body.matchAll(/<path fill="([^"]*)" d="([^"]*)"\/>/g)]
    .map(([, fill, d]) => {
      /* The paper is not painted: the circle shows through. Anything unnamed is ink, as it rendered before. */
      if (fill === "var(--avatar-white)") return "";
      const colour = fill === "var(--avatar-gray)" ? GRAY : INK;
      return `<path fill="${colour}" d="${d}"/>`;
    })
    .join("");
  const x = (index % COLUMNS) * TILE;
  const y = Math.floor(index / COLUMNS) * TILE;
  return paths ? `<g transform="translate(${x} ${y})">${paths}</g>` : "";
});

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${COLUMNS * TILE} ${rows * TILE}" width="${COLUMNS * TILE}" height="${rows * TILE}" shape-rendering="crispEdges">${cells.join("")}</svg>`;

const layout = `/* GENERATED by scripts/generate-expressive-avatar-atlas.ts: do not edit. */

/**
 * Where each tile of the bundled tileset is. A tileset is ONE image, a grid of ${TILE}px cells: the tile
 * named names[i] is at column (i % columns), row floor(i / columns). A tileset of your own keeps this
 * order for the tiles it replaces and may add its own names after them.
 */
export const expressiveAvatarAtlasLayout = {
  tileSize: ${TILE},
  columns: ${COLUMNS},
  rows: ${rows},
  names: ${JSON.stringify(names)} as readonly string[],
} as const;
`;

/* The image itself is a data URL in a stylesheet, once, not in every avatar's markup. */
const css = `/*
 * GENERATED by scripts/generate-expressive-avatar-atlas.ts: do not edit.
 *
 * The bundled tileset: ONE image (${COLUMNS} by ${rows} cells of ${TILE}px), set as the atlas every
 * expressive avatar draws from. Import it for the default face; leave it out and set
 * \`--sk-expressive-avatar-atlas\` (or pass \`tileset.src\`) to use your own.
 */
@layer components {
  :root {
    --sk-expressive-avatar-atlas: url("data:image/svg+xml,${encodeURIComponent(svg).replace(/"/g, "%22")}");
  }
}
`;

writeFileSync(new URL("../src/expressive-avatar-atlas.ts", import.meta.url), layout);
writeFileSync(new URL("../css/components/expressive-avatar-tileset.css", import.meta.url), css);
writeFileSync(new URL("../../../apps/docs/public/expressive-avatar/atlas.svg", import.meta.url), svg);
console.log(`${names.length} tiles, ${COLUMNS}x${rows} grid, atlas ${svg.length} bytes`);
