/* GENERATED by scripts/generate-expressive-avatar-atlas.ts: do not edit. */

/**
 * Where each tile of the bundled tileset is. A tileset is ONE image, a grid of 25px cells: the tile
 * named names[i] is at column (i % columns), row floor(i / columns). A tileset of your own keeps this
 * order for the tiles it replaces and may add its own names after them.
 */
export const expressiveAvatarAtlasLayout = {
  tileSize: 25,
  columns: 8,
  rows: 8,
  names: ["base-tile-00","base-tile-01","base-tile-02","base-tile-03","base-tile-04","base-tile-05","base-tile-06","base-tile-07","base-tile-08","base-tile-09","base-tile-10","base-tile-11","base-tile-12","base-tile-13","base-tile-14","base-tile-15","base-tile-16","base-tile-17","base-tile-18","base-tile-19","base-tile-20","base-tile-21","base-tile-22","left-eye-base","left-eye-top-left","left-eye-top","left-eye-top-right","left-eye-left","left-eye-right","left-eye-bottom-left","left-eye-bottom","left-eye-bottom-right","left-eye-blink","right-eye-base","right-eye-top-left","right-eye-top","right-eye-top-right","right-eye-left","right-eye-right","right-eye-bottom-left","right-eye-bottom","right-eye-bottom-right","right-eye-blink","right-eye-wink","mouth-rest-left","neutral-slight-open-left","closed-m-b-p-left","a-wide-open-left","e-mid-open-left","i-tight-stretched-left","o-rounded-left","u-tight-rounded-left","smile-left","mouth-rest-right","neutral-slight-open-right","closed-m-b-p-right","a-wide-open-right","e-mid-open-right","i-tight-stretched-right","o-rounded-right","u-tight-rounded-right","smile-right","hat-empty"] as readonly string[],
} as const;
