import type { StorybookConfig } from "@storybook/react-vite";
import { sharedVite, staticDirs } from "@skryensya/storybook-kit/vite";

/*
 * THE REACT STORYBOOK. Its stories are its own (`src/stories`, generated by `pnpm generate`), and
 * every one is drawn by `renderTree` through `src/tree-story.tsx`. The Vanilla Storybook
 * (`apps/storybook-vanilla`) is a separate app with its own copy; nothing here reads it.
 */
const config: StorybookConfig = {
  framework: "@storybook/react-vite",
  addons: ["@storybook/addon-docs"],
  stories: ["../src/**/*.stories.ts"],
  staticDirs,
  core: { disableTelemetry: true },
  viteFinal: async (vite) => sharedVite(vite),
};

export default config;
