// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/accordion.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/accordion.css";
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/details.css";
import "@skryensya/core/components/diagram.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/accordion";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Surfaces & Collections/Accordion", tags: ["autodocs"] } satisfies Meta;

export const DetailsAnatomy: StoryObj = treeStory(demos.detailsAnatomyTree);
export const Single: StoryObj = treeStory(demos.accordionSingleTree);
export const Exclusive: StoryObj = treeStory(demos.accordionExclusiveTree);
export const Multiple: StoryObj = treeStory(demos.accordionMultipleTree);
export const Closed: StoryObj = treeStory(demos.accordionClosedTree);
export const DontVerbose: StoryObj = treeStory(demos.accordionDontVerboseTree);
export const DetailsGroup: StoryObj = treeStory(demos.detailsGroupTree);
export const Choice: StoryObj = treeStory(demos.accordionChoiceTree);
