// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/app-shell.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/callout.css";
import "@skryensya/core/components/navbar.css";
import "@skryensya/core/components/sidebar.css";
import "@skryensya/core/components/stat.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/nav-list.css";
import "@skryensya/core/patterns/splitter.css";
import "@skryensya/core/patterns/vaul.css";
import "@skryensya/core/patterns/wrapper.css";
import * as demos from "@docs/demos/app-shell";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/AppShell/AppShell", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.appShellTree);
export const Explorer: StoryObj = treeStory(demos.appShellExplorerTree);
