// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/appearance.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/accordion.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/details.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/appearance";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/Appearance", tags: ["autodocs"] } satisfies Meta;

export const Specimen: StoryObj = treeStory(demos.appearanceSpecimenTree);
