// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/audio-player.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/audio-player.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/list.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/audio-player";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Media & Visuals/Audio Player", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.audioPlayerAnatomyTree);
export const Default: StoryObj = treeStory(demos.audioPlayerTree);
export const Card: StoryObj = treeStory(demos.audioPlayerCardTree);
export const Playlist: StoryObj = treeStory(demos.audioPlayerPlaylistTree);
export const Minimal: StoryObj = treeStory(demos.audioPlayerMinimalTree);
export const DoName: StoryObj = treeStory(demos.audioPlayerDoNameTree);
export const DontName: StoryObj = treeStory(demos.audioPlayerDontNameTree);
export const DoRoom: StoryObj = treeStory(demos.audioPlayerDoRoomTree);
export const DontRoom: StoryObj = treeStory(demos.audioPlayerDontRoomTree);
