// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/avatar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/avatar";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Labels & Identity/Avatar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.avatarAnatomyTree);
export const GroupAnatomy: StoryObj = treeStory(demos.avatarGroupAnatomyTree);
export const Single: StoryObj = treeStory((t) => demos.avatarSingleTree());
export const Image: StoryObj = treeStory(demos.avatarImageTree);
export const Sizes: StoryObj = treeStory(demos.avatarSizesTree);
export const Colors: StoryObj = treeStory(demos.avatarColorsTree);
export const Group: StoryObj = treeStory(demos.avatarGroupTree);
export const Profile: StoryObj = treeStory(demos.avatarProfileTree);
export const CompactRow: StoryObj = treeStory((t) => demos.avatarCompactRowTree());
export const DontOversizedRow: StoryObj = treeStory((t) => demos.avatarDontOversizedRowTree());
export const ColorIdentity: StoryObj = treeStory(demos.avatarColorIdentityTree);
export const DontStatusColor: StoryObj = treeStory(demos.avatarDontStatusColorTree);
export const DontAlone: StoryObj = treeStory((t) => demos.avatarDontAloneTree());
export const DontLongRow: StoryObj = treeStory(demos.avatarDontLongRowTree);
