// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/calendar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/calendar.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/calendar";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Calendar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.calendarAnatomyTree);
export const Default: StoryObj = treeStory(demos.calendarTree);
export const Range: StoryObj = treeStory(demos.calendarRangeTree);
export const MinMax: StoryObj = treeStory(demos.calendarMinMaxTree);
export const DontTwo: StoryObj = treeStory(demos.calendarDontTwoTree);
