// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/card-guide.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/card-guide";
import { cardCopy } from "@docs/examples/card-data";
import { treeStory, localeOf, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Card/CardGuide", tags: ["autodocs"] } satisfies Meta;

export const CardDontInnerLink: StoryObj = treeStory((t) => demos.cardDontInnerLinkTree(cardCopy[localeOf(t)], "#"));
