// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/command-palette.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/command-palette.css";
import "@skryensya/core/components/dialog.css";
import "@skryensya/core/patterns/dialog-vaul.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/command-palette";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Actions/CommandPalette", tags: ["autodocs"] } satisfies Meta;

export const Demo: StoryObj = treeStory(demos.commandPaletteDemoTree);
