// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/data-grid.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/data-grid.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/data-grid";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Unlisted/DataGrid", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.dataGridAnatomyTree);
export const Scores: StoryObj = treeStory(demos.dataGridScoresTree);
export const Actions: StoryObj = treeStory(demos.dataGridActionsTree);
