// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/date-picker.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/calendar.css";
import "@skryensya/core/components/date-picker.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/date-picker";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/DatePicker", tags: ["autodocs"] } satisfies Meta;

export const NativeDatePicker: StoryObj = treeStory(demos.nativeDatePickerTree);
export const Default: StoryObj = treeStory(demos.datePickerTree);
export const Disabled: StoryObj = treeStory(demos.datePickerDisabledTree);
