// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/density.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/slider.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/density";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/Density", tags: ["autodocs"] } satisfies Meta;

export const Lab: StoryObj = treeStory(demos.densityLabTree);
