// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/description-list.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/description-list.css";
import "@skryensya/core/components/tag.css";
import "@skryensya/core/components/typography.css";
import * as demos from "@docs/demos/description-list";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/DescriptionList", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.descriptionListAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.descriptionListTree);
export const Columns: StoryObj = treeStory(demos.descriptionListColumnsTree);
export const Divided: StoryObj = treeStory(demos.descriptionListDividedTree);
export const Rich: StoryObj = treeStory(demos.descriptionListRichTree);
