// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/diagram.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/diagram.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/media-gradient.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/diagram";
const { diagramAnatomyCss, diagramFlowCss, diagramCycleCss, diagramTreeCss, diagramDemoCss, diagramHalfAdderCss, diagramGateRuleCss, diagramModelCss, diagramZonedCss, diagramAwsCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Diagram", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.diagramAnatomyTree, { decorators: [withCss(diagramAnatomyCss)] });
export const Flow: StoryObj = treeStory(demos.diagramFlowTree, { decorators: [withCss(diagramFlowCss)] });
export const Branch: StoryObj = treeStory(demos.diagramBranchTree, { decorators: [withCss(diagramCycleCss)] });
export const Default: StoryObj = treeStory(demos.diagramTreeTree, { decorators: [withCss(diagramTreeCss)] });
export const Canvas: StoryObj = treeStory(demos.diagramCanvasTree, { decorators: [withCss(diagramDemoCss)] });
export const State: StoryObj = treeStory(demos.diagramStateTree, { decorators: [withCss(diagramCycleCss)] });
export const Process: StoryObj = treeStory(demos.diagramProcessTree, { decorators: [withCss(diagramDemoCss)] });
export const Logic: StoryObj = treeStory(demos.diagramLogicTree, { decorators: [withCss(diagramDemoCss)] });
export const Gate: StoryObj = treeStory(demos.diagramGateTree, { decorators: [withCss(diagramHalfAdderCss)] });
export const GateRule: StoryObj = treeStory(demos.diagramGateRuleTree, { decorators: [withCss(diagramGateRuleCss)] });
export const Model: StoryObj = treeStory(demos.diagramModelTree, { decorators: [withCss(diagramModelCss)] });
export const Infra: StoryObj = treeStory(demos.diagramInfraTree, { decorators: [withCss(diagramZonedCss)] });
export const Aws: StoryObj = treeStory(demos.diagramAwsTree, { decorators: [withCss(diagramAwsCss)] });
