// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/dialog-stack.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/dialog-stack.css";
import * as demos from "@docs/demos/dialog-stack";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Dialog Stack", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.dialogStackTree);
