// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/dialog.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/dialog.css";
import "@skryensya/core/components/list.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/dialog-vaul.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/dialog";
const { dialogAnatomyCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Dialog", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.dialogAnatomyTree, { decorators: [withCss(dialogAnatomyCss)] });
export const Confirm: StoryObj = treeStory(demos.dialogConfirmTree);
export const Vaul: StoryObj = treeStory(demos.dialogVaulTree);
