// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/dialog.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/dialog.css";
import "@skryensya/core/components/list.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/dialog-vaul.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/dialog";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Dialog", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.dialogAnatomyTree);
export const Confirm: StoryObj = treeStory(demos.dialogConfirmTree);
export const ClearConfirm: StoryObj = treeStory(demos.dialogClearConfirmTree);
export const UnsafeFocus: StoryObj = treeStory(demos.dialogUnsafeFocusTree);
export const UnsavedChanges: StoryObj = treeStory(demos.dialogUnsavedChangesTree);
export const Invite: StoryObj = treeStory(demos.dialogInviteTree);
export const RevokeAccess: StoryObj = treeStory(demos.dialogRevokeAccessTree);
export const Vague: StoryObj = treeStory(demos.dialogVagueTree);
export const Notice: StoryObj = treeStory(demos.dialogNoticeTree);
export const LongTask: StoryObj = treeStory(demos.dialogLongTaskTree);
export const Vaul: StoryObj = treeStory(demos.dialogVaulTree);
