// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/dodont-labels.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/segmented.css";
import "@skryensya/core/components/separator.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/dodont-labels";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Actions/Clipboard/DodontLabels", tags: ["autodocs"] } satisfies Meta;

export const SeparatorWordDo: StoryObj = treeStory(demos.separatorWordDoTree);
export const SeparatorWordDont: StoryObj = treeStory(demos.separatorWordDontTree);
export const SegmentedShapeDo: StoryObj = treeStory(demos.segmentedShapeDoTree);
export const SegmentedShapeDont: StoryObj = treeStory(demos.segmentedShapeDontTree);
