// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/drawer.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/nav-list.css";
import "@skryensya/core/patterns/vaul.css";
import * as demos from "@docs/demos/drawer";
import { vaulAnatomyCss } from "@docs/demos/vaul";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Drawer/Drawer", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.drawerAnatomyTree, { decorators: [withCss(vaulAnatomyCss)] });
export const Default: StoryObj = treeStory(demos.drawerTree);
