// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/editor.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/editor.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/popover.css";
import "@skryensya/core/components/toolbar.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/editor";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Editor", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.editorAnatomyTree);
export const Default: StoryObj = treeStory(demos.editorTree);
export const Compact: StoryObj = treeStory(demos.editorCompactTree);
export const DontSingleLine: StoryObj = treeStory(demos.editorDontSingleLineTree);
