// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/elevation.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/elevation";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/Elevation", tags: ["autodocs"] } satisfies Meta;

export const Scale: StoryObj = treeStory(() => demos.elevationScaleTree);
export const BoxSurfaces: StoryObj = treeStory(() => demos.elevationBoxSurfacesTree);
