// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/empty-state.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/empty-state.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/empty-state";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Feedback/EmptyState", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.emptyStateAnatomyTree);
export const Default: StoryObj = treeStory(demos.emptyStateTree);
export const DontVague: StoryObj = treeStory(demos.emptyStateDontVagueTree);
export const SearchDoGuide: StoryObj = treeStory(demos.emptyStateSearchDoGuideTree);
export const SearchDontGuide: StoryObj = treeStory(demos.emptyStateSearchDontGuideTree);
export const FirstDoGuide: StoryObj = treeStory(demos.emptyStateFirstDoGuideTree);
export const FirstDontGuide: StoryObj = treeStory(demos.emptyStateFirstDontGuideTree);
export const LoadingDo: StoryObj = treeStory(demos.emptyStateLoadingDoTree);
export const LoadingDont: StoryObj = treeStory(demos.emptyStateLoadingDontTree);
export const Search: StoryObj = treeStory(demos.emptyStateSearchTree);
