// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/expressive-avatar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/expressive-avatar.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/expressive-avatar";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Labels & Identity/Expressive Avatar", tags: ["autodocs"] } satisfies Meta;

export const DoFrame: StoryObj = treeStory(demos.expressiveAvatarDoFrameTree);
export const DontFrame: StoryObj = treeStory(demos.expressiveAvatarDontFrameTree);
export const DoState: StoryObj = treeStory(demos.expressiveAvatarDoStateTree);
export const DontState: StoryObj = treeStory(demos.expressiveAvatarDontStateTree);
export const DoCharacter: StoryObj = treeStory(demos.expressiveAvatarDoCharacterTree);
export const DontCharacter: StoryObj = treeStory(demos.expressiveAvatarDontCharacterTree);
