// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/layout-anatomy.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/footer.css";
import "@skryensya/core/patterns/hero.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/wrapper.css";
import * as demos from "@docs/demos/layout-anatomy";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Box/LayoutAnatomy", tags: ["autodocs"] } satisfies Meta;

export const BoxAnatomy: StoryObj = treeStory(demos.boxAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const StackAnatomy: StoryObj = treeStory(demos.stackAnatomyTree);
export const InlineAnatomy: StoryObj = treeStory(demos.inlineAnatomyTree);
export const GridAnatomy: StoryObj = treeStory(demos.gridAnatomyTree);
export const LayoutGridAnatomy: StoryObj = treeStory(demos.layoutGridAnatomyTree);
export const WrapperAnatomy: StoryObj = treeStory(demos.wrapperAnatomyTree);
export const HeroAnatomy: StoryObj = treeStory(demos.heroAnatomyTree);
export const FooterAnatomy: StoryObj = treeStory(demos.footerAnatomyTree);
