// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/lightbox.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/lightbox.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-overlay.css";
import "@skryensya/core/patterns/scroll-lock.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/lightbox";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Lightbox", tags: ["autodocs"] } satisfies Meta;

export const DoGalleryDd: StoryObj = treeStory(demos.lightboxDoGalleryDdTree);
export const DontStaticDd: StoryObj = treeStory(demos.lightboxDontStaticDdTree);
export const DoCaptionDd: StoryObj = treeStory(demos.lightboxDoCaptionDdTree);
export const DontNoCaptionDd: StoryObj = treeStory(demos.lightboxDontNoCaptionDdTree);
export const DoCardDd: StoryObj = treeStory(demos.lightboxDoCardDdTree);
export const DontImageOnlyDd: StoryObj = treeStory(demos.lightboxDontImageOnlyDdTree);
export const Gallery: StoryObj = treeStory(demos.lightboxGalleryTree);
export const Single: StoryObj = treeStory(demos.lightboxSingleTree);
export const Caption: StoryObj = treeStory(demos.lightboxCaptionTree);
export const Tiny: StoryObj = treeStory(demos.lightboxTinyTree);
export const Loop: StoryObj = treeStory(demos.lightboxLoopTree);
