// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/link.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import * as demos from "@docs/demos/link";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Link", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.linkAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.linkTree);
export const TileLink: StoryObj = treeStory(demos.tileLinkTree);
