// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/listbox.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/listbox.css";
import * as demos from "@docs/demos/listbox";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Listbox", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.listboxAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Single: StoryObj = treeStory(demos.listboxSingleTree);
export const Multiple: StoryObj = treeStory(demos.listboxMultipleTree);
export const Horizontal: StoryObj = treeStory(demos.listboxHorizontalTree);
