// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/loader.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/loader";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Feedback/Loader", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.loaderAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Simulation: StoryObj = treeStory(demos.loaderSimulationTree);
export const Contexts: StoryObj = treeStory(demos.loaderContextsTree);
export const StaggeredVariants: StoryObj = treeStory(demos.loaderStaggeredVariantsTree);
export const Sizes: StoryObj = treeStory(demos.loaderSizesTree);
export const Speeds: StoryObj = treeStory(demos.loaderSpeedsTree);
export const PseudoVariants: StoryObj = treeStory(demos.loaderPseudoVariantsTree);
export const HookPlayground: StoryObj = treeStory(demos.loaderHookPlaygroundTree);
export const Single: StoryObj = treeStory(demos.loaderSingleTree);
