// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/media-overlay.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-overlay.css";
import * as demos from "@docs/demos/media-overlay";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Media & Visuals/MediaOverlay", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.mediaOverlayAnatomyTree);
export const Card: StoryObj = treeStory(demos.mediaOverlayCardTree);
export const Edges: StoryObj = treeStory((t) => demos.mediaOverlayEdgesTree());
export const Strengths: StoryObj = treeStory((t) => demos.mediaOverlayStrengthsTree());
export const DoShortText: StoryObj = treeStory(demos.mediaOverlayDoShortTextTree);
export const DontLongText: StoryObj = treeStory(demos.mediaOverlayDontLongTextTree);
export const DoShade: StoryObj = treeStory(demos.mediaOverlayDoShadeTree);
export const DontNoShade: StoryObj = treeStory(demos.mediaOverlayDontNoShadeTree);
export const DoStrength: StoryObj = treeStory(demos.mediaOverlayDoStrengthTree);
export const DontStrength: StoryObj = treeStory(demos.mediaOverlayDontStrengthTree);
