// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/megamenu.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/megamenu.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-overlay.css";
import "@skryensya/core/patterns/nav-list.css";
import * as demos from "@docs/demos/megamenu";
import { placeholderHrefs } from "@docs/lib/placeholder-hrefs";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Megamenu", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.megamenuAnatomyTree);
export const Default: StoryObj = treeStory(demos.megamenuTree);
export const TwoColumns: StoryObj = treeStory((t) => demos.megamenuTwoColumnsTree(t, placeholderHrefs()));
export const FourColumns: StoryObj = treeStory((t) => demos.megamenuFourColumnsTree(t, placeholderHrefs()));
export const ThreeColumns: StoryObj = treeStory((t) => demos.megamenuThreeColumnsTree(t, placeholderHrefs()));
export const DoNamedLinks: StoryObj = treeStory(demos.megamenuDoNamedLinksTree);
export const DontVagueLinks: StoryObj = treeStory(demos.megamenuDontVagueLinksTree);
export const DoShortColumns: StoryObj = treeStory(demos.megamenuDoShortColumnsTree);
export const DontLongColumn: StoryObj = treeStory(demos.megamenuDontLongColumnTree);
export const DoShortTriggers: StoryObj = treeStory(demos.megamenuDoShortTriggersTree);
export const DontLongTriggers: StoryObj = treeStory(demos.megamenuDontLongTriggersTree);
