// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/megamenu.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/megamenu.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/media-gradient.css";
import "@skryensya/core/patterns/nav-list.css";
import * as demos from "@docs/demos/megamenu";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Megamenu", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.megamenuTree);
