// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/meter.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/meter.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/meter";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/Meter", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.meterAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.meterTree);
export const Single: StoryObj = treeStory(demos.meterSingleTree);
export const DoTone: StoryObj = treeStory(demos.meterDoToneTree);
export const DontTone: StoryObj = treeStory(demos.meterDontToneTree);
export const DontTask: StoryObj = treeStory(demos.meterDontTaskTree);
