// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/morph-stack.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/morph-stack.css";
import "@skryensya/core/components/placeholder.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/morph-stack";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Media & Visuals/Morph Stack", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.morphStackAnatomyTree);
export const Default: StoryObj = treeStory(demos.morphStackTree);
export const Turn: StoryObj = treeStory(demos.morphStackTurnTree);
export const Tuned: StoryObj = treeStory(demos.morphStackTunedTree);
export const Inverse: StoryObj = treeStory(demos.morphStackInverseTree);
export const TurnPlayground: StoryObj = treeStory(demos.morphStackTurnPlaygroundTree);
export const Layers: StoryObj = treeStory(demos.morphStackLayersTree);
