// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/number-field.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/number-field.css";
import * as demos from "@docs/demos/number-field";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/NumberField", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.numberFieldAnatomyTree);
export const Default: StoryObj = treeStory(demos.numberFieldTree);
export const Single: StoryObj = treeStory(demos.numberFieldSingleTree);
export const DontApprox: StoryObj = treeStory(demos.numberFieldDontApproxTree);
