// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/pagination.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/pagination.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/pagination";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Pagination", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.paginationAnatomyTree);
export const Default: StoryObj = treeStory(demos.paginationTree);
export const DontFew: StoryObj = treeStory(demos.paginationDontFewTree);
export const DoBelow: StoryObj = treeStory(demos.paginationDoBelowTree);
export const DontAbove: StoryObj = treeStory(demos.paginationDontAboveTree);
