// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/questionnaire.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/file-upload.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/kbd.css";
import "@skryensya/core/components/progress.css";
import "@skryensya/core/components/questionnaire.css";
import "@skryensya/core/components/radio-group.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/components/steps.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/questionnaire";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Questionnaire", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.questionnaireAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.questionnaireTree);
export const ChoicesOnly: StoryObj = treeStory(demos.questionnaireChoicesOnlyTree);
export const Likert: StoryObj = treeStory(demos.questionnaireLikertTree);
export const Branching: StoryObj = treeStory(demos.questionnaireBranchingTree);
export const FollowUp: StoryObj = treeStory(demos.questionnaireFollowUpTree);
export const Control: StoryObj = treeStory(demos.questionnaireControlTree);
export const Bar: StoryObj = treeStory(demos.questionnaireBarTree);
export const Steps: StoryObj = treeStory(demos.questionnaireStepsTree);
export const Segments: StoryObj = treeStory(demos.questionnaireSegmentsTree);
export const Rail: StoryObj = treeStory(demos.questionnaireRailTree);
export const Shortcuts: StoryObj = treeStory(demos.questionnaireShortcutsTree);
