// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/rating.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/rating.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/rating";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/Rating", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.ratingAnatomyTree);
export const Display: StoryObj = treeStory(demos.ratingDisplayTree);
export const Input: StoryObj = treeStory(demos.ratingInputTree);
export const Fractions: StoryObj = treeStory(demos.ratingFractionsTree);
export const Sizes: StoryObj = treeStory(demos.ratingSizesTree);
export const DontNoCount: StoryObj = treeStory(demos.ratingDontNoCountTree);
export const DontInputAverage: StoryObj = treeStory(demos.ratingDontInputAverageTree);
export const Playground: StoryObj = treeStory(demos.ratingPlaygroundTree);
export const ThreeSteps: StoryObj = treeStory(demos.ratingThreeStepsTree);
export const FiveSteps: StoryObj = treeStory(demos.ratingFiveStepsTree);
export const TenSteps: StoryObj = treeStory(demos.ratingTenStepsTree);
export const Hearts: StoryObj = treeStory(demos.ratingHeartsTree);
export const Product: StoryObj = treeStory(demos.ratingProductTree);
export const Review: StoryObj = treeStory(demos.ratingReviewTree);
