// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/resizable.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/resizable.css";
import "@skryensya/core/components/typography.css";
import * as demos from "@docs/demos/resizable";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Resizable", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.resizableAnatomyTree);
export const Horizontal: StoryObj = treeStory(demos.resizableHorizontalTree);
export const Vertical: StoryObj = treeStory(demos.resizableVerticalTree);
export const Three: StoryObj = treeStory(demos.resizableThreeTree);
export const Specimen: StoryObj = treeStory(demos.resizableSpecimenTree);
