// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/scroll-stack.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/scroll-stack.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/scroll-stack";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Scroll Stack", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.scrollStackAnatomyTree);
export const Default: StoryObj = treeStory(demos.scrollStackTree);
export const Product: StoryObj = treeStory(demos.scrollStackProductTree);
export const Cards: StoryObj = treeStory(demos.scrollStackCardsTree);
export const Five: StoryObj = treeStory(demos.scrollStackFiveTree);
export const Offset: StoryObj = treeStory(demos.scrollStackOffsetTree);
export const DoOpaque: StoryObj = treeStory(demos.scrollStackDoOpaqueTree);
export const DontOpaque: StoryObj = treeStory(demos.scrollStackDontOpaqueTree);
export const DoFit: StoryObj = treeStory(demos.scrollStackDoFitTree);
export const DontFit: StoryObj = treeStory(demos.scrollStackDontFitTree);
export const DoOffset: StoryObj = treeStory(demos.scrollStackDoOffsetTree);
export const DontOffset: StoryObj = treeStory(demos.scrollStackDontOffsetTree);
