// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/scroll-stack.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/scroll-stack.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/scroll-stack";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Scroll Stack", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.scrollStackTree);
