// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/scroll-expand.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/scroll-expand.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-overlay.css";
import * as demos from "@docs/demos/scroll-expand";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Scroll Expand", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.scrollExpandAnatomyTree);
export const Default: StoryObj = treeStory(demos.scrollExpandTree);
export const Interface: StoryObj = treeStory(demos.scrollExpandInterfaceTree);
export const Wide: StoryObj = treeStory(demos.scrollExpandWideTree);
export const Contract: StoryObj = treeStory(demos.scrollExpandContractTree);
export const DoCentre: StoryObj = treeStory(demos.scrollExpandDoCentreTree);
export const DontCentre: StoryObj = treeStory(demos.scrollExpandDontCentreTree);
