// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/scrollbar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/scrollbar";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Utilities/Scrollbar", tags: ["autodocs"] } satisfies Meta;

export const Always: StoryObj = treeStory(demos.scrollbarAlwaysTree);
export const Reveal: StoryObj = treeStory(demos.scrollbarRevealTree);
export const Horizontal: StoryObj = treeStory(demos.scrollbarHorizontalTree);
export const Custom: StoryObj = treeStory(demos.scrollbarCustomTree);
export const DontShort: StoryObj = treeStory(demos.scrollbarDontShortTree);
