// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/segmented.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/segmented.css";
import * as demos from "@docs/demos/segmented";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/SegmentedControl", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.segmentedAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.segmentedTree);
