// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/sidebar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/sidebar.css";
import "@skryensya/core/components/tree-view.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/nav-list.css";
import "@skryensya/core/patterns/splitter.css";
import * as demos from "@docs/demos/sidebar";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Sidebar", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.sidebarAnatomyTree);
export const Default: StoryObj = treeStory(demos.sidebarTree);
export const FloatingTrigger: StoryObj = treeStory(demos.sidebarFloatingTriggerTree);
export const Resizable: StoryObj = treeStory(demos.sidebarResizableTree);
