// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/skip-link.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/skip-link.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/skip-link";
const { skipLinkAnatomyCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/SkipLink", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.skipLinkAnatomyTree, { decorators: [withCss(skipLinkAnatomyCss)] });
export const Default: StoryObj = treeStory(demos.skipLinkTree);
export const Pair: StoryObj = treeStory(demos.skipLinkPairTree);
