// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/state-layer.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/state-layer";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/StateLayer", tags: ["autodocs"] } satisfies Meta;

export const Bare: StoryObj = treeStory(demos.stateLayerBareTree);
export const CurrentColor: StoryObj = treeStory(demos.stateLayerCurrentColorTree);
export const Lab: StoryObj = treeStory(demos.stateLayerLabTree);
