// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/styling-hooks.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/styling-hooks";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/StylingHooks", tags: ["autodocs"] } satisfies Meta;

export const StylingHookOverride: StoryObj = treeStory(demos.stylingHookOverrideTree);
