// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/table-pager.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/pagination.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/table-pager.css";
import * as demos from "@docs/demos/table-pager";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/TablePager", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tablePagerAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.tablePagerTree);
export const Minimal: StoryObj = treeStory(demos.tablePagerMinimalTree);
