// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/tags-input.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/tag.css";
import "@skryensya/core/components/tags-input.css";
import * as demos from "@docs/demos/tags-input";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/TagsInput", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tagsInputAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.tagsInputTree);
export const Empty: StoryObj = treeStory(demos.tagsInputEmptyTree);
export const Max: StoryObj = treeStory(demos.tagsInputMaxTree);
export const ReadOnly: StoryObj = treeStory(demos.tagsInputReadOnlyTree);
export const Field: StoryObj = treeStory(demos.tagsInputFieldTree);
export const DontLong: StoryObj = treeStory(demos.tagsInputDontLongTree);
export const DoShort: StoryObj = treeStory(demos.tagsInputDoShortTree);
