// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/tile.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/tile";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Tile", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tileAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const LinkDemo: StoryObj = treeStory(demos.tileLinkDemoTree);
export const ButtonDemo: StoryObj = treeStory(demos.tileButtonDemoTree);
export const ExpandableTile: StoryObj = treeStory(demos.expandableTileTree);
export const Appearance: StoryObj = treeStory(demos.tileAppearanceTree);
export const LinkGrid: StoryObj = treeStory(demos.tileLinkGridTree);
export const ButtonGroup: StoryObj = treeStory(demos.tileButtonGroupTree);
export const VersusBox: StoryObj = treeStory(demos.tileVersusBoxTree);
export const Padding: StoryObj = treeStory(demos.tilePaddingTree);
export const Single: StoryObj = treeStory(demos.tileSingleTree);
