// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/timeline.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/timeline.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/timeline";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Timeline", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.timelineAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.timelineTree);
export const Tones: StoryObj = treeStory(demos.timelineTonesTree);
export const DoTime: StoryObj = treeStory(demos.timelineDoTimeTree);
export const DontTime: StoryObj = treeStory(demos.timelineDontTimeTree);
export const DontTone: StoryObj = treeStory(demos.timelineDontToneTree);
