// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/tooltip.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/tooltip.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/tooltip";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Tooltip", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.tooltipTree);
export const DoIcon: StoryObj = treeStory(demos.tooltipDoIconTree);
export const DontLong: StoryObj = treeStory(demos.tooltipDontLongTree);
export const DontRepeat: StoryObj = treeStory(demos.tooltipDontRepeatTree);
