// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/treegrid.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/components/treegrid.css";
import * as demos from "@docs/demos/treegrid";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/Treegrid", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.treegridAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Inbox: StoryObj = treeStory(demos.treegridInboxTree);
export const Stress: StoryObj = treeStory(demos.treegridStressTree);
