// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/typography.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/typography";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Heading", tags: ["autodocs"] } satisfies Meta;

export const HeadingAnatomy: StoryObj = treeStory(demos.headingAnatomyTree);
export const TextAnatomy: StoryObj = treeStory(demos.textAnatomyTree);
export const Code: StoryObj = treeStory(demos.codeTree);
export const Output: StoryObj = treeStory(demos.outputTree);
export const HeadingDisplay: StoryObj = treeStory(demos.headingDisplayTree);
export const HeadingDocument: StoryObj = treeStory(demos.headingDocumentTree);
export const HeadingPageTitle: StoryObj = treeStory(demos.headingPageTitleTree);
export const HeadingOutline: StoryObj = treeStory(demos.headingOutlineTree);
export const HeadingCompact: StoryObj = treeStory(demos.headingCompactTree);
export const HeadingDoLevels: StoryObj = treeStory(demos.headingDoLevelsTree);
export const HeadingDontSkipLevel: StoryObj = treeStory(demos.headingDontSkipLevelTree);
export const HeadingDoOneH1: StoryObj = treeStory(demos.headingDoOneH1Tree);
export const HeadingDontManyH1: StoryObj = treeStory(demos.headingDontManyH1Tree);
export const HeadingDoVisualSize: StoryObj = treeStory(demos.headingDoVisualSizeTree);
export const HeadingDontVisualLevel: StoryObj = treeStory(demos.headingDontVisualLevelTree);
export const HeadingDoEyebrow: StoryObj = treeStory(demos.headingDoEyebrowTree);
export const HeadingDontEyebrow: StoryObj = treeStory(demos.headingDontEyebrowTree);
export const HeadingDoContent: StoryObj = treeStory(demos.headingDoContentTree);
export const HeadingDontContent: StoryObj = treeStory(demos.headingDontContentTree);
export const HeadingFlush: StoryObj = treeStory(demos.headingFlushTree);
export const TextScale: StoryObj = treeStory((t) => demos.textScaleTree());
export const TextTitle: StoryObj = treeStory(demos.textTitleTree);
export const TextReading: StoryObj = treeStory(demos.textReadingTree);
export const TextInline: StoryObj = treeStory(demos.textInlineTree);
export const TextFeedback: StoryObj = treeStory(demos.textFeedbackTree);
