// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/user-select.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/combobox.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/components/user-select.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/user-select";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/UserSelect", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.userSelectTree);
export const Multiple: StoryObj = treeStory(demos.userSelectMultipleTree);
export const Loading: StoryObj = treeStory(demos.userSelectLoadingTree);
