// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/vaul.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/list.css";
import "@skryensya/core/components/radio-group.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/vaul.css";
import * as demos from "@docs/demos/vaul";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Drawer/Vaul", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.vaulAnatomyTree);
export const Share: StoryObj = treeStory(demos.vaulShareTree);
export const Delete: StoryObj = treeStory(demos.vaulDeleteTree);
export const Filters: StoryObj = treeStory(demos.vaulFiltersTree);
