// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/window.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/window.css";
import * as demos from "@docs/demos/window";
const { windowAnatomyCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Overlays/Window", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.windowAnatomyTree, { decorators: [withCss(windowAnatomyCss)] });
export const Default: StoryObj = treeStory(demos.windowTree);
export const Fixed: StoryObj = treeStory(demos.windowFixedTree);
