// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/wrapper.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/wrapper.css";
import * as demos from "@docs/demos/wrapper";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Wrapper", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.wrapperTree);
export const DoBox: StoryObj = treeStory(demos.wrapperDoBoxTree);
export const DontPaint: StoryObj = treeStory(demos.wrapperDontPaintTree);
