// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/back-to-top.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/back-to-top.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/back-to-top";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/BackToTop/BackToTop", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.backToTopAnatomyTree);
export const Default: StoryObj = treeStory(demos.backToTopTree);
export const Scroll: StoryObj = treeStory(demos.backToTopScrollTree);
