// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/badge.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/badge";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Badge", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.badgeAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Tag: StoryObj = treeStory(demos.badgeTagTree);
export const Small: StoryObj = treeStory(demos.badgeSmallTree);
export const Dots: StoryObj = treeStory(demos.badgeDotsTree);
export const Pulse: StoryObj = treeStory(demos.badgePulseTree);
export const Holders: StoryObj = treeStory(demos.badgeHoldersTree);
