// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/button.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/button";
import { annotationDemoCss } from "@docs/demos/annotation";
const { buttonBrutalistStatesCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Actions/Button", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.buttonAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Appearance: StoryObj = treeStory(demos.buttonAppearanceTree);
export const BrutalistMatrix: StoryObj = treeStory(demos.buttonBrutalistMatrixTree);
export const BrutalistRadius: StoryObj = treeStory(demos.buttonBrutalistRadiusTree);
export const BrutalistStates: StoryObj = treeStory(demos.buttonBrutalistStatesTree, { decorators: [withCss(buttonBrutalistStatesCss)] });
export const BrutalistShapes: StoryObj = treeStory(demos.buttonBrutalistShapesTree);
export const FrostedBackdrops: StoryObj = treeStory(demos.buttonFrostedBackdropsTree);
export const FrostedMatrix: StoryObj = treeStory(demos.buttonFrostedMatrixTree);
export const FrostedRadius: StoryObj = treeStory(demos.buttonFrostedRadiusTree);
export const FrostedStates: StoryObj = treeStory(demos.buttonFrostedStatesTree);
export const FrostedShapes: StoryObj = treeStory(demos.buttonFrostedShapesTree);
export const Default: StoryObj = treeStory(demos.buttonDefaultTree);
export const Variant: StoryObj = treeStory(demos.buttonVariantTree);
export const DestructivePair: StoryObj = treeStory(demos.buttonDestructivePairTree);
export const Sizes: StoryObj = treeStory(demos.buttonSizesTree);
export const Icon: StoryObj = treeStory(demos.buttonIconTree);
export const IconOnly: StoryObj = treeStory(demos.buttonIconOnlyTree);
export const AsLink: StoryObj = treeStory(demos.buttonAsLinkTree);
export const FirstComponentButtons: StoryObj = treeStory(demos.firstComponentButtonsTree);
export const TileButton: StoryObj = treeStory(demos.tileButtonTree);
