// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/card.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/stat.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import * as demos from "@docs/demos/card";
import { cardCopy } from "@docs/examples/card-data";
import { treeStory, localeOf, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Card/Card", tags: ["autodocs"] } satisfies Meta;

export const PlainMedia: StoryObj = treeStory((t) => demos.cardPlainMediaTree(cardCopy[localeOf(t)]));
export const Basic: StoryObj = treeStory((t) => demos.cardBasicTree(cardCopy[localeOf(t)]));
export const MetaStory: StoryObj = treeStory((t) => demos.cardMetaTree(cardCopy[localeOf(t)]));
export const Stat: StoryObj = treeStory((t) => demos.cardStatTree(cardCopy[localeOf(t)]));
export const Select: StoryObj = treeStory((t) => demos.cardSelectTree(cardCopy[localeOf(t)]));
export const Link: StoryObj = treeStory((t) => demos.cardLinkTree(cardCopy[localeOf(t)]));
export const Action: StoryObj = treeStory((t) => demos.cardActionTree(cardCopy[localeOf(t)]));
export const Media: StoryObj = treeStory((t) => demos.cardMediaTree(cardCopy[localeOf(t)]));
export const Gradient: StoryObj = treeStory((t) => demos.cardGradientTree(cardCopy[localeOf(t)]));
export const MediaLink: StoryObj = treeStory((t) => demos.cardMediaLinkTree(cardCopy[localeOf(t)]));
export const Product: StoryObj = treeStory((t) => demos.cardProductTree(cardCopy[localeOf(t)]));
