// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/comment-thread.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/comment-thread.css";
import "@skryensya/core/components/dialog.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/components/placeholder.css";
import "@skryensya/core/patterns/dialog-vaul.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/comment-thread";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/CommentThread", tags: ["autodocs"] } satisfies Meta;

export const CommentAnatomy: StoryObj = treeStory(demos.commentAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const CommentActions: StoryObj = treeStory(demos.commentActionsTree);
export const CommentLikes: StoryObj = treeStory(demos.commentLikesTree);
export const Default: StoryObj = treeStory(demos.commentThreadTree);
export const Fixed: StoryObj = treeStory(demos.commentThreadFixedTree);
export const CommentDeep: StoryObj = treeStory(demos.commentDeepTree);
export const InfiniteScroll: StoryObj = treeStory(demos.commentThreadInfiniteScrollTree);
export const CommentAlone: StoryObj = treeStory(demos.commentAloneTree);
export const CommentSkeleton: StoryObj = treeStory(demos.commentSkeletonTree);
