// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/component-preview.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/code-preview.css";
import "@skryensya/core/components/component-preview.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/component-preview";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/ComponentPreview", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.componentPreviewAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Button: StoryObj = treeStory(demos.componentPreviewButtonTree);
export const Screens: StoryObj = treeStory(demos.componentPreviewScreensTree);
export const Bare: StoryObj = treeStory(demos.componentPreviewBareTree);
