// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/diagram.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/diagram.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/media-overlay.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/diagram";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Diagram", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.diagramAnatomyTree);
export const Flow: StoryObj = treeStory(demos.diagramFlowTree);
export const Branch: StoryObj = treeStory(demos.diagramBranchTree);
export const Default: StoryObj = treeStory(demos.diagramTreeTree);
export const Canvas: StoryObj = treeStory(demos.diagramCanvasTree);
export const State: StoryObj = treeStory(demos.diagramStateTree);
export const Process: StoryObj = treeStory(demos.diagramProcessTree);
export const Model: StoryObj = treeStory(demos.diagramModelTree);
export const Logic: StoryObj = treeStory(demos.diagramLogicTree);
export const Gate: StoryObj = treeStory(demos.diagramGateTree);
export const GateRule: StoryObj = treeStory(demos.diagramGateRuleTree);
export const Infra: StoryObj = treeStory(demos.diagramInfraTree);
export const Aws: StoryObj = treeStory(demos.diagramAwsTree);
export const GuideBranch: StoryObj = treeStory(demos.diagramGuideBranchTree);
export const GuideLinear: StoryObj = treeStory(demos.diagramGuideLinearTree);
export const DontLongEdge: StoryObj = treeStory(demos.diagramDontLongEdgeTree);
