// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/dock.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/dock.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/dock";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Actions/Dock", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.dockTree);
export const Size: StoryObj = treeStory((t) => demos.dockSizeTree(t, "#"));
export const Surface: StoryObj = treeStory((t) => demos.dockSurfaceTree(t, "#"));
