// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/dodont-mocks.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/dodont-mocks";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/AppShell/DodontMocks", tags: ["autodocs"] } satisfies Meta;

export const AppShellOneDo: StoryObj = treeStory(demos.appShellOneDoTree);
export const AppShellOneDont: StoryObj = treeStory(demos.appShellOneDontTree);
export const AppShellMainDo: StoryObj = treeStory(demos.appShellMainDoTree);
export const AppShellMainDont: StoryObj = treeStory(demos.appShellMainDontTree);
export const WindowTitleDo: StoryObj = treeStory(demos.windowTitleDoTree);
export const WindowTitleDont: StoryObj = treeStory(demos.windowTitleDontTree);
export const WindowBesideDo: StoryObj = treeStory(demos.windowBesideDoTree);
export const WindowBesideDont: StoryObj = treeStory(demos.windowBesideDontTree);
export const VaulActionDo: StoryObj = treeStory(demos.vaulActionDoTree);
export const VaulActionDont: StoryObj = treeStory(demos.vaulActionDontTree);
export const VaulTitleDo: StoryObj = treeStory(demos.vaulTitleDoTree);
export const VaulTitleDont: StoryObj = treeStory(demos.vaulTitleDontTree);
export const TourTitleDo: StoryObj = treeStory(demos.tourTitleDoTree);
export const TourTitleDont: StoryObj = treeStory(demos.tourTitleDontTree);
export const TourLengthDo: StoryObj = treeStory(demos.tourLengthDoTree);
export const TourLengthDont: StoryObj = treeStory(demos.tourLengthDontTree);
export const UserSelectEmailDo: StoryObj = treeStory(demos.userSelectEmailDoTree);
export const UserSelectEmailDont: StoryObj = treeStory(demos.userSelectEmailDontTree);
export const UserSelectNameDo: StoryObj = treeStory(demos.userSelectNameDoTree);
export const UserSelectNameDont: StoryObj = treeStory(demos.userSelectNameDontTree);
export const PresenceFramesDo: StoryObj = treeStory(demos.presenceFramesDoTree);
export const PresenceFramesDont: StoryObj = treeStory(demos.presenceFramesDontTree);
export const PresenceSpaceDo: StoryObj = treeStory(demos.presenceSpaceDoTree);
export const PresenceSpaceDont: StoryObj = treeStory(demos.presenceSpaceDontTree);
