// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/fade-edge.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/fade-edge.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/list.css";
import "@skryensya/core/components/tag.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/fade-edge";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/FadeEdge", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.fadeEdgeAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const FadeBottom: StoryObj = treeStory(() => demos.fadeBottomTree);
export const FadeTop: StoryObj = treeStory(() => demos.fadeTopTree);
export const FadeRight: StoryObj = treeStory(() => demos.fadeRightTree);
export const FadeLeft: StoryObj = treeStory(() => demos.fadeLeftTree);
export const FadeColor: StoryObj = treeStory(() => demos.fadeColorTree);
export const FadeIntensity: StoryObj = treeStory(() => demos.fadeIntensityTree);
export const FadeScrollAware: StoryObj = treeStory(() => demos.fadeScrollAwareTree);
