// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/folder.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/folder.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import * as demos from "@docs/demos/folder";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/Folder", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.folderAnatomyTree);
export const Default: StoryObj = treeStory(demos.folderTree);
export const Plain: StoryObj = treeStory(demos.folderPlainTree);
export const Active: StoryObj = treeStory(demos.folderActiveTree);
export const Sunken: StoryObj = treeStory(demos.folderSunkenTree);
export const Raised: StoryObj = treeStory(demos.folderRaisedTree);
export const Appearance: StoryObj = treeStory(demos.folderAppearanceTree);
