// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/form-field.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/form-field";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/FormField", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.formFieldAnatomyTree);
export const Default: StoryObj = treeStory(demos.formFieldTree);
export const AroundSelect: StoryObj = treeStory(demos.formFieldAroundSelectTree);
export const DoLabel: StoryObj = treeStory(demos.formFieldDoLabelTree);
export const DontLabel: StoryObj = treeStory(demos.formFieldDontLabelTree);
export const DoHint: StoryObj = treeStory(demos.formFieldDoHintTree);
export const DontHint: StoryObj = treeStory(demos.formFieldDontHintTree);
export const DoError: StoryObj = treeStory(demos.formFieldDoErrorTree);
export const DontError: StoryObj = treeStory(demos.formFieldDontErrorTree);
export const DoRequired: StoryObj = treeStory(demos.formFieldDoRequiredTree);
export const DontRequired: StoryObj = treeStory(demos.formFieldDontRequiredTree);
export const DoOneQuestion: StoryObj = treeStory(demos.formFieldDoOneQuestionTree);
export const DontOneQuestion: StoryObj = treeStory(demos.formFieldDontOneQuestionTree);
export const DoTextarea: StoryObj = treeStory(demos.formFieldDoTextareaTree);
export const DontTextarea: StoryObj = treeStory(demos.formFieldDontTextareaTree);
export const DoPurpose: StoryObj = treeStory(demos.formFieldDoPurposeTree);
export const DontPurpose: StoryObj = treeStory(demos.formFieldDontPurposeTree);
export const DoServerError: StoryObj = treeStory(demos.formFieldDoServerErrorTree);
export const DontServerError: StoryObj = treeStory(demos.formFieldDontServerErrorTree);
export const DoOptional: StoryObj = treeStory(demos.formFieldDoOptionalTree);
export const DontOptional: StoryObj = treeStory(demos.formFieldDontOptionalTree);
