// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/form-field.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/form-field";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/FormField", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.formFieldAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const AroundSelect: StoryObj = treeStory(demos.formFieldAroundSelectTree);
export const Default: StoryObj = treeStory(demos.formFieldTree);
export const DoHint: StoryObj = treeStory(demos.formFieldDoHintTree);
export const DontHint: StoryObj = treeStory(demos.formFieldDontHintTree);
