// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/icons.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/icons";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/Icons", tags: ["autodocs"] } satisfies Meta;

export const IconVocab: StoryObj = treeStory(() => demos.iconVocabTree);
