// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/image-cropper.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/file-upload.css";
import "@skryensya/core/components/image-cropper.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-overlay.css";
import * as demos from "@docs/demos/image-cropper";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Media & Visuals/Image Cropper", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.imageCropperAnatomyTree);
export const Default: StoryObj = treeStory(demos.imageCropperTree);
export const Avatar: StoryObj = treeStory(demos.imageCropperAvatarTree);
export const Free: StoryObj = treeStory(demos.imageCropperFreeTree);
export const Banner: StoryObj = treeStory(demos.imageCropperBannerTree);
export const Custom: StoryObj = treeStory(demos.imageCropperCustomTree);
export const Value: StoryObj = treeStory(demos.imageCropperValueTree);
export const ReadOnly: StoryObj = treeStory(demos.imageCropperReadOnlyTree);
export const Disabled: StoryObj = treeStory(demos.imageCropperDisabledTree);
export const Error: StoryObj = treeStory(demos.imageCropperErrorTree);
export const Bare: StoryObj = treeStory(demos.imageCropperBareTree);
export const Flow: StoryObj = treeStory(demos.imageCropperFlowTree);
