// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/installation.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/installation";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Foundations/Installation", tags: ["autodocs"] } satisfies Meta;

export const InstallUsage: StoryObj = treeStory(demos.installUsageTree);
