// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/layout-container.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/placeholder.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/layout-container";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Grid/LayoutContainer", tags: ["autodocs"] } satisfies Meta;

export const StackJustify: StoryObj = treeStory(demos.stackJustifyTree);
export const InlineShow: StoryObj = treeStory(demos.inlineShowTree);
export const GridSpan: StoryObj = treeStory(demos.gridSpanTree);
