// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/layout-guide.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/hero.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/layout-guide";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Layout/Grid", tags: ["autodocs"] } satisfies Meta;

export const GridDontStackCards: StoryObj = treeStory(demos.gridDontStackCardsTree);
export const GridDontDataCards: StoryObj = treeStory(demos.gridDontDataCardsTree);
export const GridDoSequence: StoryObj = treeStory(demos.gridDoSequenceTree);
export const GridDontSequence: StoryObj = treeStory(demos.gridDontSequenceTree);
export const GridDontButtons: StoryObj = treeStory(demos.gridDontButtonsTree);
export const InlineButtons: StoryObj = treeStory(demos.inlineButtonsTree);
export const InlineDoWrap: StoryObj = treeStory(demos.inlineDoWrapTree);
export const InlineDontWrap: StoryObj = treeStory(demos.inlineDontWrapTree);
export const InlineDoMetadata: StoryObj = treeStory(demos.inlineDoMetadataTree);
export const InlineDontMetadata: StoryObj = treeStory(demos.inlineDontMetadataTree);
export const InlineDoBetween: StoryObj = treeStory(demos.inlineDoBetweenTree);
export const InlineDontBetween: StoryObj = treeStory(demos.inlineDontBetweenTree);
export const HeroDontActions: StoryObj = treeStory(demos.heroDontActionsTree);
export const StackDontButtons: StoryObj = treeStory(demos.stackDontButtonsTree);
