// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/link.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/link";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Link", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.linkAnatomyTree);
export const Single: StoryObj = treeStory(demos.linkSingleTree);
export const Default: StoryObj = treeStory(demos.linkTree);
export const TileLink: StoryObj = treeStory(demos.tileLinkTree);
export const DoDescriptive: StoryObj = treeStory(demos.linkDoDescriptiveTree);
export const DontHere: StoryObj = treeStory(demos.linkDontHereTree);
export const DoTargetWords: StoryObj = treeStory(demos.linkDoTargetWordsTree);
export const DontWholeSentence: StoryObj = treeStory(demos.linkDontWholeSentenceTree);
export const DoExternal: StoryObj = treeStory(demos.linkDoExternalTree);
export const DontExternal: StoryObj = treeStory(demos.linkDontExternalTree);
export const DoAction: StoryObj = treeStory(demos.linkDoActionTree);
export const DontAction: StoryObj = treeStory(demos.linkDontActionTree);
