// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/marquee.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/marquee.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-overlay.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/marquee";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Media & Visuals/Marquee", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.marqueeAnatomyTree);
export const Manual: StoryObj = treeStory(demos.marqueeManualTree);
export const Autoplay: StoryObj = treeStory((t) => demos.marqueeAutoplayTree());
export const Control: StoryObj = treeStory(demos.marqueeControlTree);
export const Badge: StoryObj = treeStory(demos.marqueeBadgeTree);
export const Avatar: StoryObj = treeStory(demos.marqueeAvatarTree);
export const Vertical: StoryObj = treeStory(demos.marqueeVerticalTree);
export const NoFade: StoryObj = treeStory((t) => demos.marqueeNoFadeTree());
export const DoLinks: StoryObj = treeStory(demos.marqueeDoLinksTree);
export const DontLinks: StoryObj = treeStory(demos.marqueeDontLinksTree);
export const DoUniform: StoryObj = treeStory((t) => demos.marqueeDoUniformTree());
export const DontMixed: StoryObj = treeStory(demos.marqueeDontMixedTree);
export const DoFade: StoryObj = treeStory((t) => demos.marqueeDoFadeTree());
