// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/media-gradient.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import * as demos from "@docs/demos/media-gradient";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/MediaGradient", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.mediaGradientAnatomyTree);
export const Card: StoryObj = treeStory(demos.mediaGradientCardTree);
export const Edges: StoryObj = treeStory((t) => demos.mediaGradientEdgesTree());
export const Strengths: StoryObj = treeStory((t) => demos.mediaGradientStrengthsTree());
