// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/menubar.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/menu.css";
import "@skryensya/core/components/menubar.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/nav-list.css";
import * as demos from "@docs/demos/menubar";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Actions/Menubar", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.menubarTree);
export const Submenu: StoryObj = treeStory(demos.menubarSubmenuTree);
export const Nav: StoryObj = treeStory(demos.menubarNavTree);
