// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/otp-input.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/input.css";
import "@skryensya/core/components/otp-input.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/otp-input";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/OtpInput", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.otpInputAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Sms: StoryObj = treeStory(demos.otpInputSmsTree);
export const Alphanumeric: StoryObj = treeStory(demos.otpInputAlphanumericTree);
export const Pin: StoryObj = treeStory(demos.otpInputPinTree);
export const States: StoryObj = treeStory(demos.otpInputStatesTree);
export const Single: StoryObj = treeStory(demos.otpInputSingleTree);
export const DontNoHint: StoryObj = treeStory(demos.otpInputDontNoHintTree);
export const DontLong: StoryObj = treeStory(demos.otpInputDontLongTree);
export const DoLong: StoryObj = treeStory(demos.otpInputDoLongTree);
