// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/placeholder.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/avatar.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/placeholder.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/image-frame.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/media-gradient.css";
import * as demos from "@docs/demos/placeholder";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Feedback/Placeholder", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.placeholderAnatomyTree);
export const PublicationPlaceholder: StoryObj = treeStory(demos.publicationPlaceholderTree);
export const PublicationSwap: StoryObj = treeStory(demos.publicationSwapTree);
export const Match: StoryObj = treeStory(demos.placeholderMatchTree);
export const Vocabulary: StoryObj = treeStory((t) => demos.placeholderVocabularyTree());
export const Paragraph: StoryObj = treeStory((t) => demos.placeholderParagraphTree());
export const DontSlab: StoryObj = treeStory(() => demos.placeholderDontSlabTree);
