// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/procedure.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/callout.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/code-preview.css";
import "@skryensya/core/components/procedure.css";
import "@skryensya/core/components/qr-code.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/procedure";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Surfaces & Collections/Procedure", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.procedureAnatomyTree);
export const Default: StoryObj = treeStory(demos.procedureTree);
export const Deploy: StoryObj = treeStory(demos.procedureDeployTree);
export const Security: StoryObj = treeStory(demos.procedureSecurityTree);
export const DoOrder: StoryObj = treeStory(demos.procedureDoOrderTree);
export const DontOrder: StoryObj = treeStory(demos.procedureDontOrderTree);
export const DoTitles: StoryObj = treeStory(demos.procedureDoTitlesTree);
export const DontTitles: StoryObj = treeStory(demos.procedureDontTitlesTree);
export const DoActions: StoryObj = treeStory(demos.procedureDoActionsTree);
export const DontActions: StoryObj = treeStory(demos.procedureDontActionsTree);
export const DoCommand: StoryObj = treeStory(demos.procedureDoCommandTree);
export const DontCommand: StoryObj = treeStory(demos.procedureDontCommandTree);
export const Content: StoryObj = treeStory((t) => demos.procedureContentTree(t, "#"));
