// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/progress.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/progress.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/progress";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Feedback/Progress", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.progressAnatomyTree);
export const Default: StoryObj = treeStory(demos.progressTree);
export const Single: StoryObj = treeStory(demos.progressSingleTree);
export const DoRunning: StoryObj = treeStory(demos.progressDoRunningTree);
export const DontRunning: StoryObj = treeStory(demos.progressDontRunningTree);
export const DontMeasure: StoryObj = treeStory(demos.progressDontMeasureTree);
export const DoTask: StoryObj = treeStory(demos.progressDoTaskTree);
