// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/qr-code.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/badge.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/popover.css";
import "@skryensya/core/components/qr-code.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/anchored.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/qr-code";
import { treeStory, localeOf, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Content/QRCode", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory((t) => demos.qrCodeAnatomyTree(t, localeOf(t)));
export const Default: StoryObj = treeStory((t) => demos.qrCodeTree(localeOf(t)));
export const Sizes: StoryObj = treeStory((t) => demos.qrCodeSizesTree(localeOf(t)));
export const Levels: StoryObj = treeStory((t) => demos.qrCodeLevelsTree(localeOf(t)));
export const Shapes: StoryObj = treeStory((t) => demos.qrCodeShapesTree(localeOf(t)));
export const Masks: StoryObj = treeStory((t) => demos.qrCodeMasksTree(localeOf(t)));
export const Tones: StoryObj = treeStory((t) => demos.qrCodeTonesTree(localeOf(t)));
export const Logo: StoryObj = treeStory((t) => demos.qrCodeLogoTree(localeOf(t)));
export const Card: StoryObj = treeStory((t) => demos.qrCodeCardTree(localeOf(t)));
export const Popover: StoryObj = treeStory((t) => demos.qrCodePopoverTree(localeOf(t)));
export const Ticket: StoryObj = treeStory((t) => demos.qrCodeTicketTree(localeOf(t)));
export const DoWithLink: StoryObj = treeStory((t) => demos.qrCodeDoWithLinkTree(localeOf(t)));
export const DontAlone: StoryObj = treeStory((t) => demos.qrCodeDontAloneTree(localeOf(t)));
export const DoShortLink: StoryObj = treeStory((t) => demos.qrCodeDoShortLinkTree(localeOf(t)));
export const DontLongLink: StoryObj = treeStory((t) => demos.qrCodeDontLongLinkTree(localeOf(t)));
export const DoLogoLevel: StoryObj = treeStory((t) => demos.qrCodeDoLogoLevelTree(localeOf(t)));
export const DontLogoLevel: StoryObj = treeStory((t) => demos.qrCodeDontLogoLevelTree(localeOf(t)));
