// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/radio-group.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/radio-group.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/box.css";
import "@skryensya/core/patterns/layout.css";
import "@skryensya/core/patterns/wrapper.css";
import * as demos from "@docs/demos/radio-group";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/RadioGroup", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.radioGroupAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.radioGroupTree);
export const TileRadioGroup: StoryObj = treeStory(demos.tileRadioGroupTree);
export const Likert: StoryObj = treeStory(demos.radioGroupLikertTree);
export const Matrix: StoryObj = treeStory(demos.radioGroupMatrixTree);
