// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/rating.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/rating.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/rating";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/Rating", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.ratingAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Display: StoryObj = treeStory(demos.ratingDisplayTree);
export const Input: StoryObj = treeStory(demos.ratingInputTree);
export const Fractions: StoryObj = treeStory(demos.ratingFractionsTree);
export const Sizes: StoryObj = treeStory(demos.ratingSizesTree);
export const DontNoCount: StoryObj = treeStory(demos.ratingDontNoCountTree);
export const DontInputAverage: StoryObj = treeStory(demos.ratingDontInputAverageTree);
