// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/select.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/form-field.css";
import "@skryensya/core/components/select.css";
import "@skryensya/core/patterns/anchored.css";
import * as demos from "@docs/demos/select";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Select", tags: ["autodocs"] } satisfies Meta;

export const Default: StoryObj = treeStory(demos.selectTree);
export const Native: StoryObj = treeStory(demos.selectNativeTree);
