// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/slider.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/slider.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/slider";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Slider", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.sliderAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Default: StoryObj = treeStory(demos.sliderTree);
export const Range: StoryObj = treeStory(demos.sliderRangeTree);
export const DontTwo: StoryObj = treeStory(demos.sliderDontTwoTree);
export const DoRange: StoryObj = treeStory(demos.sliderDoRangeTree);
export const DontExact: StoryObj = treeStory(demos.sliderDontExactTree);
export const DoApprox: StoryObj = treeStory(demos.sliderDoApproxTree);
