// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/steps.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/steps.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/steps";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Steps", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.stepsAnatomyTree);
export const Default: StoryObj = treeStory(demos.stepsTree);
export const Vertical: StoryObj = treeStory(demos.stepsVerticalTree);
export const DontMany: StoryObj = treeStory(demos.stepsDontManyTree);
export const DontColor: StoryObj = treeStory(demos.stepsDontColorTree);
