// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/switch.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/checkbox.css";
import "@skryensya/core/components/switch.css";
import "@skryensya/core/components/tile.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/switch";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Forms/Switch", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.switchAnatomyTree);
export const Default: StoryObj = treeStory(demos.switchTree);
export const TileSwitch: StoryObj = treeStory(demos.tileSwitchTree);
export const DontSave: StoryObj = treeStory(demos.switchDontSaveTree);
export const DoCheckbox: StoryObj = treeStory(demos.switchDoCheckboxTree);
