// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/table.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/table.css";
import "@skryensya/core/patterns/box.css";
import * as demos from "@docs/demos/table";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Data/Table", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tableAnatomyTree);
export const Default: StoryObj = treeStory(demos.tableTree);
export const StickyColumn: StoryObj = treeStory(demos.tableStickyColumnTree);
export const ResizableColumns: StoryObj = treeStory(demos.tableResizableColumnsTree);
export const StickyHeader: StoryObj = treeStory(demos.tableStickyHeaderTree);
export const InBox: StoryObj = treeStory(demos.tableInBoxTree);
export const DeploymentsTable: StoryObj = treeStory(demos.deploymentsTable);
export const Density: StoryObj = treeStory(demos.tableDensityTree);
export const DontList: StoryObj = treeStory(demos.tableDontListTree);
