// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/tabs.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/tabs.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/tabs";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Tabs", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tabsAnatomyTree);
export const Basic: StoryObj = treeStory(demos.tabsBasicTree);
export const States: StoryObj = treeStory(demos.tabsStatesTree);
export const Advanced: StoryObj = treeStory(demos.tabsAdvancedTree);
export const Size: StoryObj = treeStory(demos.tabsSizeTree);
export const Hanging: StoryObj = treeStory(demos.tabsHangingTree);
export const DontMany: StoryObj = treeStory(demos.tabsDontManyTree);
export const DontSteps: StoryObj = treeStory(demos.tabsDontStepsTree);
