// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/tag.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/tag.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/tag";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Labels & Identity/Tag", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tagAnatomyTree);
export const Simple: StoryObj = treeStory(demos.tagSimpleTree);
export const Tones: StoryObj = treeStory(demos.tagTonesTree);
export const Links: StoryObj = treeStory(demos.tagLinksTree);
export const Removable: StoryObj = treeStory(demos.tagRemovableTree);
