// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/toast.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/callout.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/toast.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/toast";
const { toastAnatomyCss } = demos;
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Feedback/Toast", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.toastAnatomyTree, { decorators: [withCss(toastAnatomyCss)] });
export const Emit: StoryObj = treeStory(demos.toastEmitTree);
export const Simple: StoryObj = treeStory(demos.toastSimpleTree);
export const Status: StoryObj = treeStory(demos.toastStatusTree);
export const Action: StoryObj = treeStory(demos.toastActionTree);
export const Stack: StoryObj = treeStory(demos.toastStackTree);
