// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/toc.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/toc.css";
import "@skryensya/core/patterns/icon.css";
import * as demos from "@docs/demos/toc";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/Table of contents", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.tocAnatomyTree);
export const Plain: StoryObj = treeStory(demos.tocPlainTree);
export const Nested: StoryObj = treeStory(demos.tocNestedTree);
export const Icons: StoryObj = treeStory(demos.tocIconsTree);
export const DontLong: StoryObj = treeStory(demos.tocDontLongTree);
