// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/tree-view.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/tree-view.css";
import "@skryensya/core/components/typography.css";
import "@skryensya/core/patterns/icon.css";
import "@skryensya/core/patterns/layout.css";
import * as demos from "@docs/demos/tree-view";
import { annotationDemoCss } from "@docs/demos/annotation";
import { treeStory, withCss, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Navigation/TreeView", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.treeViewAnatomyTree, { decorators: [withCss(annotationDemoCss)] });
export const Minimal: StoryObj = treeStory(demos.treeViewMinimalTree);
export const Initial: StoryObj = treeStory(demos.treeViewInitialTree);
export const Multiple: StoryObj = treeStory(demos.treeViewMultipleTree);
export const Disabled: StoryObj = treeStory(demos.treeViewDisabledTree);
export const Events: StoryObj = treeStory(demos.treeViewEventsTree);
