// GENERATED by @skryensya/storybook-kit from apps/docs/src/demos/video-player.ts. Do not edit;
// change the demo (or the docs page that shows it) and run `pnpm generate` in this app.
import "@skryensya/core/components/annotation.css";
import "@skryensya/core/components/button.css";
import "@skryensya/core/components/canvas.css";
import "@skryensya/core/components/loader.css";
import "@skryensya/core/components/video-player.css";
import "@skryensya/core/patterns/visually-hidden.css";
import * as demos from "@docs/demos/video-player";
import { treeStory, type Meta, type StoryObj } from "../tree-story";

export default { title: "Components/Media & Visuals/Video Player", tags: ["autodocs"] } satisfies Meta;

export const Anatomy: StoryObj = treeStory(demos.videoPlayerAnatomyTree);
export const Default: StoryObj = treeStory(demos.videoPlayerTree);
export const Study: StoryObj = treeStory(demos.videoPlayerStudyTree);
export const DoPoster: StoryObj = treeStory(demos.videoPlayerDoPosterTree);
export const DontPoster: StoryObj = treeStory(demos.videoPlayerDontPosterTree);
export const DoRoom: StoryObj = treeStory(demos.videoPlayerDoRoomTree);
export const DontRoom: StoryObj = treeStory(demos.videoPlayerDontRoomTree);
