import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createHash, createHmac } from "node:crypto";
export interface Asset {
  bytes: Uint8Array;
  contentType: "image/png" | "application/json";
}
export interface AssetStore {
  put(key: string, asset: Asset): Promise<void>;
  get(key: string): Promise<Asset | undefined>;
}
const safeKey = (key: string) => {
  if (
    !/^[a-zA-Z0-9][a-zA-Z0-9/-]*\.(png|json)$/.test(key) ||
    key.includes("..")
  )
    throw new Error("Invalid asset key");
  return key;
};
const contentType = (key: string): Asset["contentType"] =>
  key.endsWith(".png") ? "image/png" : "application/json";
export function memoryAssets(): AssetStore {
  const data = new Map<string, Asset>();
  return {
    async put(key, asset) {
      data.set(safeKey(key), structuredClone(asset));
    },
    async get(key) {
      return structuredClone(data.get(safeKey(key)));
    },
  };
}
export function filesystemAssets(root: string): AssetStore {
  return {
    async put(key, asset) {
      const file = resolve(root, safeKey(key));
      await mkdir(resolve(file, ".."), { recursive: true });
      await writeFile(file, asset.bytes);
    },
    async get(key) {
      try {
        return {
          bytes: await readFile(resolve(root, safeKey(key))),
          contentType: contentType(key),
        };
      } catch (e) {
        if ((e as NodeJS.ErrnoException).code === "ENOENT") return undefined;
        throw e;
      }
    },
  };
}
/** SigV4 path-style S3/R2 transport. Asset keys are generated by the server, never page paths. */
export function s3Assets(
  config: {
    endpoint: string;
    bucket: string;
    region: string;
    accessKeyId: string;
    secretAccessKey: string;
  },
  transport: typeof fetch = fetch,
): AssetStore {
  const hash = (value: string | Uint8Array) =>
    createHash("sha256").update(value).digest("hex");
  const sign = (key: string | Buffer, value: string) =>
    createHmac("sha256", key).update(value).digest();
  async function request(method: string, key: string, asset?: Asset) {
    const url = new URL(
      `${config.endpoint.replace(/\/$/, "")}/${encodeURIComponent(config.bucket)}/${safeKey(key).split("/").map(encodeURIComponent).join("/")}`,
    );
    const date = new Date().toISOString().replace(/[:-]|\.\d{3}/g, "");
    const day = date.slice(0, 8),
      payload = hash(asset?.bytes ?? "");
    const canonicalHeaders = `host:${url.host}\nx-amz-content-sha256:${payload}\nx-amz-date:${date}\n`;
    const signedHeaders = "host;x-amz-content-sha256;x-amz-date";
    const scope = `${day}/${config.region}/s3/aws4_request`;
    const canonical = `${method}\n${url.pathname}\n\n${canonicalHeaders}\n${signedHeaders}\n${payload}`;
    const signature = sign(
      sign(
        sign(sign(`AWS4${config.secretAccessKey}`, day), config.region),
        "s3",
      ),
      "aws4_request",
    );
    const auth = `AWS4-HMAC-SHA256 Credential=${config.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${sign(signature, `AWS4-HMAC-SHA256\n${date}\n${scope}\n${hash(canonical)}`).toString("hex")}`;
    const response = await transport(url, {
      method,
      headers: {
        authorization: auth,
        "x-amz-date": date,
        "x-amz-content-sha256": payload,
        ...(asset ? { "content-type": asset.contentType } : {}),
      },
      body: asset ? Buffer.from(asset.bytes) : undefined,
      signal: AbortSignal.timeout(60_000),
    });
    if (!response.ok && response.status !== 404)
      throw new Error(`Asset store failed: ${response.status}`);
    return response;
  }
  return {
    async put(key, asset) {
      const r = await request("PUT", key, asset);
      if (!r.ok) throw new Error("Asset upload failed");
    },
    async get(key) {
      const r = await request("GET", key);
      return r.status === 404
        ? undefined
        : {
            bytes: new Uint8Array(await r.arrayBuffer()),
            contentType: contentType(key),
          };
    },
  };
}
