import { tools } from "./tools.js";

/*
 * The README's tool table, rendered from the declarations in `tools.ts` rather than written by hand.
 * The previous README listed three tools and a workflow the server had already outgrown; nothing
 * could notice. `pnpm --filter @skryensya/mcp docs` rewrites the block, and `docs.test.ts` fails when
 * the committed block differs from what this renders.
 */
export const TOOLS_START = "<!-- tools:start (generated by `pnpm --filter @skryensya/mcp docs`, do not edit) -->";
export const TOOLS_END = "<!-- tools:end -->";

export function renderToolTable(): string {
  const rows = tools.map((tool, at) => `| ${at + 1} | \`${tool.name}\` | ${tool.summary} |`);
  return [TOOLS_START, "", "| # | Tool | What it returns |", "|---|---|---|", ...rows, "", TOOLS_END].join("\n");
}

/** Replaces the generated block in `markdown`, or throws when the markers are missing. */
export function withToolTable(markdown: string): string {
  const start = markdown.indexOf(TOOLS_START);
  const end = markdown.indexOf(TOOLS_END);
  if (start === -1 || end === -1 || end < start) throw new Error("README is missing the tools:start / tools:end markers.");
  return markdown.slice(0, start) + renderToolTable() + markdown.slice(end + TOOLS_END.length);
}
