/*
 * Generates the Phosphor set from the library's assets.
 *
 * Phosphor does not publish data: it publishes `.svg` files (`assets/regular/*.svg`). That is why there
 * is a generator here and none for the manifest, see decision 15. The allowlist reimplemented the
 * bundler's tree-shaking and did nothing; this converts a format no bundler converts on its own. Delete
 * it and the consumer parses SVG at runtime or ties itself to `?raw`, which is Vite's. The complexity
 * reappears, so the layer does something.
 *
 * The library stays a devDependency: the consumer's bundle receives 32 icons and nothing else.
 *
 * The shell (--check, the template, the `<svg>` extraction) is shared by all three sets and lives in
 * @skryensya/core/emit-icon-set. What is left here is only what varies: the MAP, the ATTRS, the header,
 * and the asset spec. `resolve` runs in THIS module on purpose: `import.meta.resolve` has to see
 * Phosphor's devDependency, which core does not have.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { generateIconSet, extractSvgBody } from "@skryensya/core/emit-icon-set";

/* System role → Phosphor's name. The role is ours and the name is theirs: `search` is their
 * `magnifying-glass`, and that distance is exactly what the stable vocabulary buys. */
const MAP = {
  "chevron-up": "caret-up",
  "chevron-down": "caret-down",
  "chevron-left": "caret-left",
  "chevron-right": "caret-right",
  "arrow-up": "arrow-up",
  "vote-up": "arrow-fat-up",
  "vote-down": "arrow-fat-down",
  "arrow-down": "arrow-down",
  "arrow-left": "arrow-left",
  "arrow-right": "arrow-right",
  "external-link": "arrow-square-out",
  add: "plus",
  remove: "minus",
  close: "x",
  check: "check",
  search: "magnifying-glass",
  edit: "pencil-simple",
  delete: "trash",
  copy: "copy",
  filter: "funnel",
  refresh: "arrows-clockwise",
  "zoom-out": "magnifying-glass-minus",
  more: "dots-three",
  menu: "list",
  info: "info",
  success: "check-circle",
  warning: "warning",
  danger: "x-circle",
  calendar: "calendar",
  clock: "clock",
  upload: "upload",
  download: "download",
  file: "file",
  folder: "folder",
  settings: "gear",
  user: "user",
  language: "translate",
  visibility: "eye",
  "visibility-off": "eye-slash",
  "mode-system": "monitor",
  "mode-light": "sun",
  "mode-dark": "moon",
  "screen-desktop": "monitor",
  "screen-tablet": "device-tablet",
  "screen-mobile": "device-mobile",
};

/* Phosphor draws FILLED shapes, not strokes, even at the `regular` weight, which looks like outline but
 * is filled outlines. Its SVGs already carry fill="currentColor" on the root; we re-declare it here
 * anyway so IconData is explicit and does not depend on the asset staying the same. */
const ATTRS = { fill: "currentColor" };

const WEIGHT = "regular";

const HEADER = `/*
 * GENERATED by scripts/generate.ts, do not edit by hand.
 *
 * Phosphor Icons geometry (MIT), "${WEIGHT}" weight, redistributed under its license.
 * See LICENSE-phosphor.
 */`;

/** Phosphor's adapter: resolve the `.svg` asset from the devDependency and extract its body. */
const resolve = (name: string, role: string) => {
  const spec = `@phosphor-icons/core/assets/${WEIGHT}/${name}.svg`;
  let path;
  try {
    path = fileURLToPath(import.meta.resolve(spec));
  } catch {
    throw new Error(`Phosphor no tiene "${name}" (rol "${role}"), ¿se renombró en un upgrade?`);
  }
  return extractSvgBody(readFileSync(path, "utf8"), name);
};

generateIconSet({ dir: import.meta.dirname, label: "phosphor", map: MAP, attrs: ATTRS, header: HEADER, resolve });
