import type { StorybookConfig } from "@storybook/html-vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { sharedVite, staticDirs } from "@skryensya/storybook-kit/vite";

/*
 * THE VANILLA STORYBOOK. Its stories are its own (`src/stories`, generated by `pnpm generate`), and
 * every one is the tree's emitted markup brought to life by the Vanilla enhancers, through
 * `src/tree-story.ts`. The React Storybook (`apps/storybook`) is a separate app; nothing here reads
 * it. The Svelte plugin is here because several enhancers are Svelte components inside.
 */
const config: StorybookConfig = {
  framework: "@storybook/html-vite",
  addons: ["@storybook/addon-docs"],
  stories: ["../src/**/*.stories.ts"],
  staticDirs,
  core: { disableTelemetry: true },
  viteFinal: async (vite) => {
    const shared = sharedVite(vite);
    return { ...shared, plugins: [...(shared.plugins ?? []), svelte()] };
  },
};

export default config;
